- Telegram/PrepareWin.bat
To record sounds like the mobile version.
> Please add a record button

- QTCREATOR.md
Qt project changed their domain to qt.io
> Updated build instructions for linux

- README.md
It also work on Fedora 22. Tested!
> Update README.md with a new supported OS

- Telegram/Resources/lang.strings
- Telegram/SourceFiles/settingswidget.cpp
- Telegram/SourceFiles/settingswidget.h
- Telegram/SourceFiles/window.cpp
- Telegram/SourceFiles/window.h
Hi,
I've added menu item to system tray context menu which toggles Display Notification setting.
Hope it might be helpfull!
> Add item to system tray to toggle notifications display

- Telegram/SourceFiles/history.cpp
Telegram Desktop Developer Certificate of Origin
By making a contribution to this project, I certify that:
(a) The contribution was created in whole by me or is based upon
previous work that, to the best of my knowledge, is in the
public domain and I have the right to put it in the public domain.
(d) I understand and agree that this project and the contribution are
public and that a record of the contribution (including all
metadata and personal information I submit with it, including my
sign-off) is maintained indefinitely and may be redistributed.
(e) I am granting this work into the public domain.
Signed-off-by: Anwesh <anwesh@gmx.com> (github: kanishkablack)
> Gnome Shell Duplicates bug fix

- XCODE.md
Fix some format, add warning on file hierarchy, fix typo and create list for readability.
> Improve XCode.md format and readability

- Telegram/SourceFiles/historywidget.cpp
Signed-off-by: Heejune Kim <heejune@gmail.com> (github: heejune)
> Resolving a bug #1247 (Sending files to channels)

- .travis.yml
- .travis/arch.sh
- .travis/build.sh
> Add Travis CI files

- doc/building-xcode.md
> Fix path in doc/building-xcode.md

- Telegram/Resources/lang.strings
- Telegram/SourceFiles/profilewidget.cpp
- Telegram/SourceFiles/profilewidget.h
Also add `lng_profile_copy_fullname` to lang.strings
I've broken my repo, so github haven't updated previous request
> Add "Copy name" option (Requested in #1783) (2)

- .travis.yml
- .travis/build.sh
- .travis/check.sh
- .travis/common.sh
Check if the commit messages of PRs contains the [signature](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) at travis
> Check commit messages

- Telegram/SourceFiles/_other/genstyles.cpp
=) Sh**ty code)
Signed-off-by: Soltan Tekeev <stek29@yandex.ru>
> Fix code duplicate

- doc/building-msvc.md
just a small fix, added cd into the directory
> Fixed doc building-msvc.md

- .travis.yml
- .travis/build.sh
- Telegram/SourceFiles/platform/linux/linux_libs.cpp
- Telegram/SourceFiles/platform/linux/linux_libs.h
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
Make possible build on system without unity (like Gentoo)
> New define: TDESKTOP_DISABLE_UNITY_INTEGRATION

- Telegram/SourceFiles/ui/scrollarea.cpp
Fix for https://github.com/telegramdesktop/tdesktop/issues/2208
> Pass Escape key to internal widget of ScrollArea

- doc/building-msvc.md
Add table of contents
Fix breakpad install
> Improve build instructions for MSVC 2015

- .travis/build.sh
How did this even build?
Errors introduced by https://github.com/telegramdesktop/tdesktop/commit/e320be96262344bc02efba13433de58691e302b7
> Fix syntax error

- doc/building-xcode-old.md
- doc/building-xcode.md
just a tiny documentation update
> Fixed FFmpeg version in Xcode build instructions

- README.md
Update README.md with a new supported OS
>  Update README.md with a new supported OS

- README.md
Its updated by adding tags
After merge: Add webhook to https://badge.fury.io/hooks/github
> Add version to the readme

- Telegram/SourceFiles/platform/linux/linux_libs.cpp
> linux-libs: parse XDG_CURRENT_DESKTOP as colon separated list

- doc/building-msvc.md
See https://github.com/telegramdesktop/tdesktop/issues/2704
> Clearer instructions for running msys2_shell.bat

- .appveyor/install.bat
- .gitattributes
- .travis/build.sh
- README.md
- Telegram/gyp/Telegram.gyp
- Telegram/gyp/refresh.bat
- appveyor.yml
- doc/building-msvc.md
Also implement build defines for Windows
Set TELEGRAM_BUILD_DEFINES before calling gyp/refresh.bat
🎉🎉
> Implement AppVeyor

- Telegram/gyp/print_version.sh
Signed-off-by: MohammadReza Espargham <reza.espargham@owasp.org> (github: rezasp)
> Added interpreter path

- .appveyor/install.bat
Maybe fixes the random clone errors
> Only clone latest commit at AppVeyor

- .appveyor/check.bat
- .appveyor/install.bat
- .travis.yml
- .travis/check.sh
- .travis/common.sh
- appveyor.yml
Check for the signature ("Signed-off-by: ..."):
> Implement signature checks

- Telegram/gyp/list_sources.py
This avoids problems with some locale settings.
> Always use UTF-8 to open files in list_sources.py

- Telegram/Resources/langs/lang.strings
- Telegram/SourceFiles/history/history_inner_widget.cpp
- Telegram/SourceFiles/history/history_item.h
- Telegram/SourceFiles/history/history_message.cpp
- Telegram/SourceFiles/history/history_message.h
This is how it looks like currently:
I'm still not sure about the wording.
> Show date from fwdHeader on tooltip

- Telegram/Patches/qtbase_5_6_2.diff
- Telegram/SourceFiles/qt_static_plugins.cpp
- Telegram/gyp/telegram_linux.gypi
Add hime support (#3129)
Signed-off-by: Zankio <xxoojoeooxx1@gmail.com>
(github: zankio)
> Add hime inputcontext plugin for linux version

- Telegram/SourceFiles/historywidget.cpp
- Telegram/SourceFiles/historywidget.h
Kinda fixes #2963, #2315, #2371.
> Don't clear undo history when applying draft

- Telegram/SourceFiles/mainwidget.cpp
See the discussion on https://github.com/telegramdesktop/tdesktop/pull/3678#pullrequestreview-55968964
> Fix updates of mute status in context menu of dialog list

- Telegram/SourceFiles/base/qthelp_regex.h
- Telegram/SourceFiles/history/history_item.h
- Telegram/SourceFiles/platform/win/main_window_win.cpp
- Telegram/SourceFiles/storage/localimageloader.h
- Telegram/SourceFiles/ui/text/text.cpp
- Probed the code with Cppcheck 1.80
> Fix small issues pointed out by static analysis

- .appveyor/install.bat
Follow-up for #3920
Signed-off-by: Duncan Ogilvie mr.exodia.tpodt@gmail.com (github: mrexodia)
> don't call vcvarsall.bat in AppVeyor script

- docs/building-msvc.md
> Added cmake to %PATH%

- Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp
- Telegram/SourceFiles/platform/linux/linux_desktop_environment.h
I fixed tray icon appearance, tooltip style, and tray context menu style for awesome WM. It should work properly on Gentoo Linux once pull request is accepted.
> awesome WM tray icon fix

- Telegram/SourceFiles/base/openssl_help.h
- Telegram/SourceFiles/mtproto/auth_key.cpp
- Telegram/SourceFiles/mtproto/rsa_public_key.cpp
Please merge this PR to compile against the latest OpenSSL 1.1
> Fix build against OpenSSL 1.1

- changelog.txt
> Remove wrong alpha version

- Telegram/SourceFiles/history/history_item.h
- Telegram/SourceFiles/history/history_widget.cpp
> Add reply shortcut

- Telegram/SourceFiles/core/utils.cpp
- Telegram/SourceFiles/mtproto/rsa_public_key.cpp
> fix build against libressl

- Telegram/SourceFiles/apiwrap.h
- Telegram/SourceFiles/base/build_config.h
- Telegram/SourceFiles/core/crash_reports.cpp
- Telegram/SourceFiles/data/data_media_types.h
- Telegram/SourceFiles/data/data_types.h
- Telegram/SourceFiles/history/history_item.h
- Telegram/SourceFiles/history/history_media.h
- Telegram/SourceFiles/info/info_content_widget.h
- Telegram/SourceFiles/info/info_memento.h
- Telegram/SourceFiles/info/info_wrap_widget.h
- Telegram/SourceFiles/info/profile/info_profile_values.h
- Telegram/SourceFiles/platform/linux/linux_glibc_wraps_32.c
- Telegram/SourceFiles/platform/linux/linux_glibc_wraps_64.c
- Telegram/SourceFiles/storage/storage_shared_media.h
- Telegram/gyp/linux_glibc_wraps.gyp
- Telegram/gyp/settings_linux.gypi
- Telegram/gyp/telegram_linux.gypi
Make telegram to compile properly in ARM hosts.
This also needs https://github.com/grishka/libtgvoip/pull/40
> Linux ARM compile fixes

- .travis/build.sh
As discussed in #4505, change some build flags
> Travis flags update

- Telegram/SourceFiles/base/weak_ptr.h
This is required for unique_ptr.
> Add include to <memory>

- README.md
> Update Fedora version

- Telegram/SourceFiles/apiwrap.cpp
Small fix for build with GCC 8.2.0
> Workaround internal compiler error in GCC

- docs/building-xcode.md
Removed redundant automake and libtool from brew install.
> Remove duplicated packages in brew install

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Refactored FallbackFontConfig() to use native Qt methods.
> Refactored FallbackFontConfig() to use native Qt methods

- LEGAL
- Telegram/Resources/winrc/Telegram.rc
- Telegram/Resources/winrc/Updater.rc
Not a very useful change to user, still ....
> Update copyright year

- docs/building-cmake.md
> docs: Fix setting the gcc-7 alternative with apt

- Telegram/SourceFiles/auth_session.cpp
- Telegram/SourceFiles/auth_session.h
- Telegram/SourceFiles/core/application.cpp
- Telegram/SourceFiles/core/application.h
- Telegram/SourceFiles/history/history_widget.cpp
- Telegram/SourceFiles/mainwidget.cpp
- Telegram/SourceFiles/mainwindow.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.h
- Telegram/SourceFiles/platform/mac/specific_mac.h
- Telegram/SourceFiles/platform/mac/specific_mac.mm
- Telegram/SourceFiles/platform/win/specific_win.cpp
- Telegram/SourceFiles/platform/win/specific_win.h
- Telegram/SourceFiles/window/main_window.cpp
- Telegram/SourceFiles/window/notifications_manager_default.cpp
- Telegram/SourceFiles/window/notifications_manager_default.h
This PR fixes [this one](https://github.com/telegramdesktop/tdesktop/issues/5695).
If you don't mind, I also added some `const` to vars within `checkAutoLock()`.
If this is not good for single commit, I'll remove it.
> Fixed auto-lock while recording voice message.

- Telegram/SourceFiles/boxes/abstract_box.cpp
There is shadow glitch when edit media box size decreases.
> Fixed redrawing of shadows when box size decreases.

- docs/building-xcode-old.md
- docs/building-xcode.md
This small PR moves existing thread parameters to one place, as it is done in cmake doc.
> Updated building-xcode.md. Moved number of threads into variable.

- .travis.yml
- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/gyp/settings_linux.gypi
- docs/building-cmake.md
Added `-y` parameters to make installation of dependencies non-interactive.
Changed order of installation for correct linking of GCC.
> Updated building-cmake.md

- Telegram/SourceFiles/platform/linux/linux_libs.cpp
> Also allow wayland GDK backend

- docs/building-cmake.md
> Add chrpath to CMake instruction

- docs/building-osx.md
- docs/building-xcode.md
> Fix building instruction of macOS

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
This PR fixes:
* https://github.com/kotatogram/kotatogram-desktop/issues/3
* https://github.com/flathub/org.telegram.desktop/issues/122
Also:
* fixes indentation
* adds support for TDESKTOP_LAUNCHER_FILENAME
* other little fixes
> Fix multiple issues in native notifications

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/10
> Change fc-custom.conf condition to DESKTOP_APP_USE_PACKAGED

- Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp
- Telegram/SourceFiles/platform/linux/linux_desktop_environment.h
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.h
- Telegram/cmake/telegram_options.cmake
This also removes unused TryUnityCounter
See also: https://github.com/desktop-app/cmake_helpers/pull/13
> Add possibility to build without dbus

- .github/workflows/mac.yml
<sub><sup>That's how ctrl-c + ctrl-v can ruin your life :)</sup></sub>
> [GH Actions] Fix artifacts path from win to mac style

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
Added missing Qt header. Fixed clang build.
> Added missing Qt header. Fixed clang build

- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.h
- Telegram/SourceFiles/qt_static_plugins.cpp
See also: https://github.com/desktop-app/cmake_helpers/pull/17
Should help with https://github.com/telegramdesktop/tdesktop/issues/2411
> Use XDG Desktop Portal for file dialog

- snap/snapcraft.yaml
For https://github.com/desktop-app/cmake_helpers/pull/18
> Adapt snap for system GSL

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.h
> Check action id when invoked

- .github/workflows/linux.yml
- Telegram/SourceFiles/mainwindow.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.h
- Telegram/SourceFiles/platform/mac/main_window_mac.mm
- Telegram/SourceFiles/qt_static_plugins.cpp
- Telegram/ThirdParty/statusnotifieritem/statusnotifieritem.cpp
- Telegram/ThirdParty/statusnotifieritem/statusnotifieritem.h
- docs/building-cmake.md
Fixes #7153, fixes #7154, fixes #7158, fixes #7163
Depends on https://github.com/desktop-app/cmake_helpers/pull/27
> Tray icon fixes

- .github/workflows/linux.yml
- Telegram/CMakeLists.txt
- Telegram/cmake/telegram_options.cmake
- docs/building-cmake.md
See also https://github.com/desktop-app/cmake_helpers/pull/30
> Move TDESKTOP_DISABLE_DBUS_INTEGRATION to cmake_helpers

- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.h
Fixes #7211, fixes #7212, fixes #7226
> Use XDG Desktop Portal only when variable is set

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.h
> Follow hidding reply setting in native notifications on Linux, use system icon

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.h
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
> A bunch of fixes for main_window_linux and specific_linux

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.h
> Fix notification daemon detection on KDE

- .github/workflows/linux.yml
- Telegram/SourceFiles/media/audio/media_audio.cpp
- Telegram/SourceFiles/media/audio/media_audio_capture.cpp
- docs/building-cmake.md
> Don't set device explicitly when capturing

- snap/snapcraft.yaml
> Update openal to fix 2x sound speed in snap

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.h
> Change tray implementation on demand

- Telegram/Resources/langs/lang.strings
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.h
> Implement global menu on Linux

- snap/snapcraft.yaml
> Use custom fontconfig file in snap to avoid problems with host fontconfig

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
> Don't recreate tray icon if it is disabled

- Telegram/CMakeLists.txt
- Telegram/cmake/telegram_options.cmake
Depends on https://github.com/desktop-app/cmake_helpers/pull/33
> Add possibility to enable autoupdate on non-special target

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
> Don't remove SNI object when SNI is lost

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
With current code fallback works only through time and replaces the config even if it is changed by the user.
This commit fixes that.
> Restore the old behavior with fallback fontconfig configuration

- .github/workflows/snap.yml
- snap/snapcraft.yaml
> Add cinnamon gsettings schema to snap

- Telegram/SourceFiles/media/streaming/media_streaming_file.cpp
- Telegram/SourceFiles/mtproto/details/mtproto_tls_socket.cpp
* Use identical types for std::min.
* See also: https://github.com/desktop-app/lib_base/pull/9
> Update GSL to v3.0.1 and lib_base

- snap/scripts/telegram-launch
- snap/snapcraft.yaml
> Show friendly warning if snapd didn't update snap right for some reason

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.h
> Detect global menu at runtime

- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
Since commits checkout are taken from the docs, docs should not be ignored by actions.
> Do not ignore changes for docs needed for build

- Telegram/SourceFiles/calls/calls_panel.cpp
> Fix call window hiding when compositing is not supported

- Telegram/SourceFiles/history/history_widget.cpp
> Remove replyTo from switchInlineBotButton in same peer

- Telegram/SourceFiles/platform/mac/notifications_manager_mac.mm
> fix: obtain doNotDisturb value correctly

- Telegram/SourceFiles/calls/calls_panel.cpp
- Telegram/SourceFiles/settings/settings_notifications.cpp
- Telegram/SourceFiles/window/notifications_manager_default.cpp
> Fix call window size and notification positioning on Sway

- Telegram/SourceFiles/core/launcher.cpp
> Disable fallback session management

- Telegram/SourceFiles/media/view/media_view_pip.cpp
- Telegram/SourceFiles/ui/widgets/separate_panel.cpp
> Apply sway fixes to the PiP and export windows too

- Telegram/SourceFiles/platform/linux/linux_libs.cpp
> Fix crash in gtk file dialog on Wayland

- Telegram/SourceFiles/window/themes/window_themes_generate_name.cpp
(Perfectionists will be happy).
> Fix little typo in theme names generator

- .github/workflows/linux.yml
- docs/building-cmake.md
Depends on https://github.com/desktop-app/patches/pull/8 https://github.com/desktop-app/cmake_helpers/pull/44
>  Add patches with the fix for #6645

- snap/snapcraft.yaml
> Fix running snap with XEmbed trays

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
> Unset QT_STYLE_OVERRIDE instead of forcing Fusion

- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/SourceFiles/platform/linux/linux_gdk_helper.cpp
- Telegram/SourceFiles/platform/linux/linux_libs.cpp
- Telegram/SourceFiles/platform/linux/linux_libs.h
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.h
> Don't load another gtk version if gtk_init_check was called

- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/platform_window_title.h
- Telegram/SourceFiles/window/window.style
- Telegram/SourceFiles/window/window_title_qt.cpp
- Telegram/SourceFiles/window/window_title_qt.h
Depends on https://github.com/desktop-app/patches/pull/11 https://github.com/desktop-app/materialdecoration/pull/3
>  Add cross-platform TitleWidget implementation based on startSystemMove/startSystemResize

- Telegram/SourceFiles/platform/linux/linux_libs.cpp
To inherit icon theme even on WM-based environments
> Always fallback to gtk icon theme

- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
- docs/building-cmake.md
- docs/building-msvc.md
- docs/building-xcode.md
To decrease actions run time and fails
> Don't build OpenSSL tests

- Telegram/SourceFiles/core/application.cpp
- Telegram/SourceFiles/core/core_settings.cpp
- Telegram/SourceFiles/core/core_settings.h
- Telegram/SourceFiles/platform/linux/linux_libs.cpp
- Telegram/SourceFiles/platform/linux/linux_libs.h
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/mac/specific_mac.h
- Telegram/SourceFiles/platform/platform_specific.h
- Telegram/SourceFiles/platform/win/specific_win.cpp
- Telegram/SourceFiles/platform/win/windows_event_filter.cpp
- Telegram/SourceFiles/settings/settings_codes.cpp
- Telegram/SourceFiles/window/window_main_menu.cpp
Implements #4918 for Windows and Linux
> Implement system-based dark mode for Windows and Linux

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/mac/specific_mac.h
- Telegram/SourceFiles/platform/platform_specific.h
- Telegram/SourceFiles/platform/win/specific_win.cpp
- Telegram/SourceFiles/window/window_title_qt.cpp
Depends on https://github.com/desktop-app/patches/pull/15
> Add support for showing window menu on Wayland

- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/SourceFiles/platform/linux/file_utilities_linux.h
> Don't focus parent window after opening file dialog

- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/58
> Add webrtc support for snap

- Telegram/SourceFiles/mainwindow.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/mac/specific_mac.h
- Telegram/SourceFiles/platform/platform_specific.h
- Telegram/SourceFiles/platform/win/specific_win.h
- Telegram/SourceFiles/window/main_window.cpp
- Telegram/SourceFiles/window/main_window.h
- Telegram/SourceFiles/window/window_title_qt.cpp
- Telegram/SourceFiles/window/window_title_qt.h
Depends on https://github.com/desktop-app/patches/pull/16
> Add main window shadow for Linux

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
> Fix d-bus type in MutterDBusLastUserInputTime

- Telegram/SourceFiles/boxes/connection_box.cpp
> Replace commas with dots in proxy address

- .github/workflows/win.yml
- docs/building-msvc.md
> Disable OpenAL WASAPI backend

- Telegram/SourceFiles/platform/win/windows_event_filter.cpp
> Fix showing autohidden taskbar with maximized window

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/window/window_title_qt.cpp
> Don't add shadow on Wayland

- Telegram/SourceFiles/window/main_window.cpp
> Don't change window flags in Window::MainWindow::recountGeometryConstraints

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
> Update SNI state even if tray is deactivated

- Telegram/SourceFiles/platform/win/windows_event_filter.cpp
> Find taskbar window on the same monitor

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.h
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.h
> Subscribe to StatusNotifierHostRegistered signal

- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/62 and https://github.com/desktop-app/lib_base/pull/17
> Use new XCB methods from lib_base

- .github/workflows/mac.yml
> Remove explicit Opus clone step from macos action

- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/docker/centos_env/build.sh
> CentOS-based Docker build

- Telegram/SourceFiles/media/audio/media_audio.cpp
On Linux, audio files that embed a cover art will not be sent with their metadata but as simple documents.
This happens because the cover art embedded in an audio file is a video stream, which makes `FFMpegAttributesReader::open()` error out. On Windows and Android (and I also guess on macOS?) this doesn't happen and the file is sent properly with its cover art.
Telegram still works, the metadata are properly encoded/decoded, I'm able to send tracks with cover arts and see them with other clients (from other OSes).
This commit fixes #5840, fixes #5357 and fixes #4327 (they're all related).
> Ignore additional video streams inside an audio file

- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
- docs/building-cmake.md
- docs/building-msvc.md
- docs/building-osx.md
- docs/building-xcode.md
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/63
> Use MozJPEG

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
IBus has changed its socket path several times and each change should be synchronized with Qt. Moreover, the last time Qt changed the path, they didn't introduce a fallback to the old path and made the new Qt incompatible with IBus from older distributions. Since tdesktop is distributed in static binary form, it makes sense to use ibus portal whenever it present to ensure compatibility with the maximum range of distributions.
> Use ibus portal whenever it present

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
More info: https://codereview.qt-project.org/c/qt/qtbase/+/314618
> Adapt linux tray icon implementation to the new QIcon::pixmap behavior

- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/68 https://github.com/desktop-app/lib_base/pull/27
> Add new dependencies to snap build

- .github/workflows/win.yml
https://github.com/kcat/openal-soft/issues/498#issuecomment-736974529
> Fix OpenAL build in Windows action

- docs/building-cmake.md
Thanks to @ilya-fedin for helping me with this!
> Update Linux build instructions

- Telegram/build/docker/centos_env/Dockerfile
There's no any session management anyway
> Build without libICE and libSM on Linux

- .github/workflows/snap.yml
- snap/snapcraft.yaml
It's supported since snapd 2.46 that was released in August
> Use ibus portal in snap

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
QIcon::actualSize doesn't work as expected with svg themes, get actual pixmap and check its size instead.
Fixes #9985
> Fix blurry tray icon with svg themes

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/29
> Use new IsSupportedByWM XCB API from lib_base

- Telegram/SourceFiles/core/launcher.cpp
- Telegram/SourceFiles/core/launcher.h
- Telegram/SourceFiles/main/main_account.cpp
- Telegram/SourceFiles/platform/linux/launcher_linux.cpp
- Telegram/SourceFiles/platform/mac/launcher_mac.mm
- Telegram/SourceFiles/platform/win/launcher_win.cpp
This allows using methods that require a running QGuiApplication instance to detect system
> Use DeviceModelPretty/SystemVersionPretty directly

- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/SourceFiles/platform/linux/linux_wayland_integration.cpp
- Telegram/SourceFiles/platform/linux/linux_wayland_integration.h
- Telegram/SourceFiles/platform/linux/linux_wayland_integration_dummy.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/linux/window_title_linux.cpp
- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/76
> Check for xdg-decoration protocol support on Wayland

- changelog.txt
fix some typos in changelog.txt
> DOC Minor Fixes

- Telegram/SourceFiles/media/streaming/media_streaming_file.cpp
> Fix checking cover stream on seeking

- Telegram/SourceFiles/window/window_title_qt.cpp
> Restore frameless hint on showing to workaround a bug in Qt

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
When checking notification inhibition support
> Don't log UnknownProperty error

- Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/build/docker/centos_env/Dockerfile
> Fix build with linked gtk

- Telegram/SourceFiles/window/window_title_qt.cpp
> Fix crash with fcitx and custom titlebar

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/build/docker/centos_env/Dockerfile
Works only with patched Qt, depends on https://github.com/desktop-app/patches/pull/26
> Another attempt to implement shadows on Wayland

- Telegram/SourceFiles/settings.h
- Telegram/SourceFiles/storage/details/storage_settings_scheme.cpp
- Telegram/SourceFiles/storage/localstorage.cpp
- Telegram/SourceFiles/window/main_window.cpp
> Take custom scale in account when saving window geometry

- Telegram/SourceFiles/window/window_title_qt.cpp
- Telegram/SourceFiles/window/window_title_qt.h
QWindow::setCursor doesn't work as expected...
> Restore QGuiApplication::setOverrideCursor usage

- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/linux/linux_gdk_helper.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/83, https://github.com/desktop-app/lib_base/pull/38, https://github.com/desktop-app/lib_ui/pull/35
> Add DESKTOP_APP_DISABLE_X11_INTEGRATION

- snap/snapcraft.yaml
> Use LZO compression in snap

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/window/main_window.cpp
Depends on https://github.com/desktop-app/lib_base/pull/39
Fixes #10431
> Use custom method to focus main window on X11

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depens on https://github.com/desktop-app/lib_ui/pull/41
> Move gtk settings connections to getters

- Telegram/SourceFiles/platform/linux/launcher_linux.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.h
Use QGuiApplication::desktopFileName directly instead
> Get rid of GetLauncherFilename

- Telegram/SourceFiles/api/api_updates.cpp
- Telegram/SourceFiles/core/file_utilities.cpp
- Telegram/SourceFiles/data/data_document.cpp
- Telegram/SourceFiles/lang/lang_file_parser.cpp
- Telegram/SourceFiles/platform/linux/launcher_linux.cpp
- Telegram/SourceFiles/storage/details/storage_file_utilities.cpp
- Telegram/SourceFiles/support/support_templates.cpp
https://github.com/KDE/clazy/blob/master/docs/checks/README-qfileinfo-exists.md
> Use static QFileInfo::exists

- Telegram/SourceFiles/apiwrap.cpp
- Telegram/SourceFiles/chat_helpers/field_autocomplete.cpp
- Telegram/SourceFiles/logs.cpp
- Telegram/SourceFiles/mainwidget.cpp
- Telegram/SourceFiles/profile/profile_block_group_members.cpp
- Telegram/SourceFiles/profile/profile_block_group_members.h
https://github.com/KDE/clazy/blob/master/docs/checks/README-qmap-with-pointer-key.md
> Use base::flat_map for pointer keys 

- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
Since it may running continously
> Use QProcess::startDetached for xdg-open

- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/linux/linux_mpris_support.cpp
- Telegram/SourceFiles/platform/linux/linux_mpris_support.h
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- snap/snapcraft.yaml
> Add MPRIS support

- Telegram/SourceFiles/platform/linux/linux_mpris_support.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/56
Fixes #10595
> Add a way to get dark mode state on KDE

- Telegram/SourceFiles/window/main_window.cpp
> Scale window icon manually when getting from icon theme

- Telegram/SourceFiles/platform/linux/linux_notification_service_watcher.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/57
> Workaround snap's activation restriction

- Telegram/SourceFiles/mtproto/mtp_instance.cpp
Allows to not to click "Try now" after connecting to Wi-Fi network
> Watch for network aviability changes

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/59
> Move GTK initialization before Qt initialization

- Telegram/SourceFiles/mainwindow.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/51
Closes #753
> Check if the window is not overlapped when is not active

- Telegram/SourceFiles/platform/linux/linux_xdp_file_dialog.cpp
I think it's finally the time to switch remaining environments (gtk-based) to portal file dialog
> Prefer portal file dialog in all environments

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/92, https://github.com/desktop-app/lib_base/pull/63
> Move wayland helper to cmake_helpers

- .gitmodules
- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
> Use mallocng on Linux

- snap/snapcraft.yaml
> A bunch of snap fixes

- Telegram/SourceFiles/core/launcher.cpp
- Telegram/SourceFiles/core/sandbox.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/56
> Adapt for Ui::DisableCustomScaling changes

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_waylandshells/pull/3
> Set QT_WAYLAND_SHELL_INTEGRATION to custom value

- Telegram/configure.py
> Shorten if statement

- .gitmodules
- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Now it's known how to make it free the memory in an expected manner and it's better maintained
Depends on https://github.com/desktop-app/cmake_helpers/pull/105
> Switch from mallocng to jemalloc

- .github/workflows/linux.yml
- Telegram/CMakeLists.txt
- Telegram/SourceFiles/core/launcher.h
- Telegram/SourceFiles/platform/linux/launcher_linux.cpp
- Telegram/SourceFiles/platform/linux/launcher_linux.h
- Telegram/SourceFiles/platform/linux/linux_gdk_helper.cpp
- Telegram/SourceFiles/platform/linux/linux_gdk_helper.h
- Telegram/SourceFiles/platform/linux/linux_gtk_integration.cpp
- Telegram/SourceFiles/platform/linux/linux_gtk_integration.h
- Telegram/SourceFiles/platform/linux/linux_gtk_integration_dummy.cpp
- Telegram/SourceFiles/platform/linux/linux_gtk_open_with_dialog.cpp
- Telegram/SourceFiles/platform/linux/linux_gtk_open_with_dialog.h
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/telegramdesktop/tdesktop/pull/16496, https://github.com/desktop-app/lib_base/pull/75, https://github.com/desktop-app/lib_webview/pull/4
> Move GTK integration out of process with D-Bus

- Telegram/SourceFiles/chat_helpers/bot_keyboard.cpp
Attempt to fix not working commands in moderator mode by using more conventional keys
> Attempt to fix not working commands

- Telegram/SourceFiles/platform/linux/launcher_linux.cpp
- Telegram/SourceFiles/platform/linux/linux_gtk_integration.cpp
- Telegram/SourceFiles/platform/linux/linux_gtk_integration.h
- Telegram/SourceFiles/platform/linux/linux_gtk_integration_dummy.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/76, https://github.com/desktop-app/lib_webview/pull/8
> Set service name for lib_base and lib_webview gtk integration

- Telegram/SourceFiles/platform/linux/linux_gtk_integration.cpp
> Fix 30s freeze after pasting

- Telegram/SourceFiles/platform/linux/linux_xdp_file_dialog.cpp
The freezing is still happening if the service is not accessible
> Right file dialog freeze fix

- Telegram/SourceFiles/boxes/peers/edit_peer_permissions_box.cpp
- Telegram/SourceFiles/core/crash_report_window.cpp
- Telegram/SourceFiles/editor/photo_editor_controls.cpp
- Telegram/SourceFiles/history/history_inner_widget.cpp
- Telegram/SourceFiles/history/view/history_view_service_message.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_opengl.cpp
- Telegram/SourceFiles/media/view/media_view_pip_opengl.cpp
- Telegram/SourceFiles/platform/linux/launcher_linux.h
- Telegram/cmake/lib_tgcalls.cmake
Fixes -Wdeprecated-enum-enum-conversion, -Wdeprecated-declarations, -Wrange-loop-construct, -Winconsistent-missing-override
> Allow to build with -Werror and clang

- Telegram/build/docker/centos_env/Dockerfile
The original command failed for me. Tried it out and the original given path was wrong. This commit fixes those patches.
> Fix applying of patches in Dockerfile.

- Telegram/CMakeLists.txt
Depends on https://github.com/desktop-app/lib_base/pull/84 https://github.com/desktop-app/lib_webview/pull/12
> Always use QLibrary for gtk to avoid confusing dynamic linker

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
> Use Communications category for tray icon

- Telegram/SourceFiles/_other/updater_linux.cpp
- Telegram/SourceFiles/_other/updater_osx.m
- Telegram/SourceFiles/_other/updater_win.cpp
- Telegram/SourceFiles/core/launcher.cpp
- Telegram/SourceFiles/platform/linux/launcher_linux.cpp
- Telegram/SourceFiles/platform/mac/launcher_mac.mm
- Telegram/SourceFiles/platform/win/launcher_win.cpp
Having a path to executable in /etc/tdesktop/externalupdater is a way more convenient and is enough
> Remove -externalupdater flag

- Telegram/SourceFiles/payments/smartglocal/smartglocal_api_client.h
- Telegram/SourceFiles/payments/smartglocal/smartglocal_callbacks.h
- Telegram/SourceFiles/payments/smartglocal/smartglocal_card.cpp
- Telegram/SourceFiles/payments/stripe/stripe_api_client.h
- Telegram/SourceFiles/payments/stripe/stripe_card_validator.cpp
- Telegram/SourceFiles/payments/stripe/stripe_card_validator.h
- Telegram/SourceFiles/payments/stripe/stripe_decode.h
- Telegram/SourceFiles/payments/stripe/stripe_form_encoder.cpp
not sure where it comes from but compiler refuses to proceed :cry:
> Mention some missing includes in payments/ subdirectory

- Telegram/Resources/langs/lang.strings
- Telegram/SourceFiles/history/history_widget.cpp
- Telegram/SourceFiles/history/history_widget.h
> Synchronize intended behavior

- Telegram/SourceFiles/core/update_checker.cpp
- Telegram/SourceFiles/platform/linux/launcher_linux.cpp
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/117
> Move LZMA usage under TDESKTOP_DISABLE_AUTOUPDATE

- Telegram/build/docker/centos_env/Dockerfile
Depends on https://github.com/desktop-app/patches/pull/52, https://github.com/desktop-app/cmake_helpers/pull/118
> Link drm & zlib statically like before, make GL optional

- Telegram/Resources/langs/lang.strings
- Telegram/SourceFiles/core/core_settings.cpp
- Telegram/SourceFiles/core/core_settings.h
- Telegram/SourceFiles/core/launcher.cpp
- Telegram/SourceFiles/core/sandbox.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/settings.cpp
- Telegram/SourceFiles/settings.h
- Telegram/SourceFiles/settings/settings_advanced.cpp
- Telegram/SourceFiles/window/main_window.cpp
- lib/xdg/telegramdesktop.desktop
> Implement close to taskbar option

- Telegram/build/docker/centos_env/Dockerfile
In combination with https://github.com/desktop-app/cmake_helpers/pull/126 gets rid of unused glib symbols
> Build glibmm with LTO

- .github/workflows/win.yml
- Telegram/build/prepare/prepare.py
Depends on https://github.com/desktop-app/patches/pull/57, https://github.com/desktop-app/cmake_helpers/pull/128
> Use opus built with cmake on Windows

- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_widget.h
> Control video in fullscreen mode using arrows and numbers

- Telegram/SourceFiles/platform/win/main_window_win.cpp
- Telegram/SourceFiles/platform/win/main_window_win.h
This allows the feature to work without patching Qt
> Inform Qt about taskbar hider

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
> Build Qt without high DPI scaling support

- .github/workflows/linux.yml
- Telegram/SourceFiles/platform/linux/launcher_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_webview/pull/17, https://github.com/desktop-app/cmake_helpers/pull/142
> Use webkitgtk without its headers

- Telegram/build/docker/centos_env/Dockerfile
There are bunch of other best practices which can help reducing the final image size or setting pipefail and so.
But as this Dockerfile is not getting used in final product, I'm not sure if it's worth putting time into it.
> Run yum clean all after package installation

- Telegram/SourceFiles/_other/updater_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
> Revert "Use kernel accelerated sendfile to copy files on Linux"

- Telegram/SourceFiles/core/utils.cpp
- Telegram/SourceFiles/mtproto/details/mtproto_rsa_public_key.cpp
> Get rid of deprecated OpenSSL <1.1 functions

- .gitmodules
- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
This will simplify packaged Qt 6 build
Depends on https://github.com/desktop-app/cmake_helpers/pull/147
> Build kwayland as external project

- .gitmodules
- Telegram/build/docker/centos_env/Dockerfile
Linux is the only platform where slow QThreadPool is used, let's use dispatch here as well
Depends on https://github.com/desktop-app/cmake_helpers/pull/145 https://github.com/desktop-app/lib_crl/pull/1
> Activate crl dispatch backend on Linux

- Telegram/build/prepare/prepare.py
git:// is not going through proxy.
> Use https:// not git:// to clone.

- Telegram/SourceFiles/media/system_media_controls_manager.cpp
- Telegram/SourceFiles/media/system_media_controls_manager.h
Depends on https://github.com/desktop-app/lib_base/pull/109
> Implement loop status/shuffle for MPRIS

- Telegram/cmake/lib_tgvoip.cmake
Depends on https://github.com/desktop-app/cmake_helpers/pull/161, https://github.com/desktop-app/lib_crl/pull/3, https://github.com/desktop-app/lib_spellcheck/pull/19, https://github.com/desktop-app/lib_webview/pull/24
> Move libdl/libpthread handling to common_options

- .gitmodules
- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/165
> Update kwayland and move its dependencies to ThirdParty to keep them in sync

- Telegram/cmake/generate_appdata_changelog.cmake
> Don't use BYPRODUCTS with appdata changelog

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/174
> Move jemalloc initialization code to cmake_helpers

- Telegram/SourceFiles/platform/linux/linux_wayland_integration.cpp
- Telegram/SourceFiles/platform/linux/linux_wayland_integration.h
- Telegram/SourceFiles/platform/linux/linux_wayland_integration_dummy.cpp
- Telegram/SourceFiles/platform/linux/linux_xdp_file_dialog.cpp
- Telegram/SourceFiles/platform/linux/linux_xdp_open_with_dialog.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/112
> Move xdg-foreign support to lib_base

- snap/snapcraft.yaml
> Disable some syscalls in snap Qt build

- Telegram/SourceFiles/chat_helpers/spellchecker_common.cpp
> Fix Hunspell spellchecking with Qt 6

- Telegram/SourceFiles/history/history_inner_widget.cpp
> Don't block main queue with drag operation

- Telegram/SourceFiles/window/main_window.cpp
> Use RpWindow's method to set minimum window size

- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_widget.h
This time with a weaker geometry check
> Try to react to move events in media viewer, again

- Telegram/SourceFiles/chat_helpers/gifs_list_widget.cpp
- Telegram/SourceFiles/dialogs/ui/dialogs_layout.cpp
- Telegram/SourceFiles/history/view/media/history_view_invoice.cpp
- Telegram/SourceFiles/inline_bots/inline_results_inner.h
> Remove unused variables

- Telegram/build/prepare/prepare.py
> Fix dir separator on windows

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
> Match socket length check with Qt

- Telegram/SourceFiles/window/main_window.cpp
There's no RpWindow::setMinimumWidth
> Replace setMinimumWidth with updateMinimumSize in Window::MainWindow

- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/prepare/prepare.py
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/90, https://github.com/desktop-app/cmake_helpers/pull/190, https://github.com/desktop-app/lib_base/pull/117, https://github.com/desktop-app/lib_waylandshells/pull/11
> Update to Qt 6.3

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/89
> Move waitForInterfaceAnnounce call to the uses of announced interfaces

- Telegram/SourceFiles/platform/linux/linux_xdp_file_dialog.cpp
- Telegram/SourceFiles/platform/linux/linux_xdp_open_with_dialog.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/118
> Adapt to lib_base's XDP API changes

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Looks like it causes problems along with -Wl,-z,now
> Disable egl-extension-platform-wayland again

- .github/workflows/mac.yml
- .github/workflows/win.yml
The caching action doesn't update the cache when cache hit is happenned.
This could be fixed by having unique keys for every cache change and using restore-keys to find these caches.
> Fix cache update for the actions

- Telegram/build/docker/centos_env/Dockerfile
Depends on https://github.com/desktop-app/cmake_helpers/pull/191
> Remove object files from the resulting Docker image

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Telegram listens for a signal that indicates when the color-scheme
changes. The signal itself includes the new value, but Telegram
currently queries for the value immediately after getting the signal.
This second round-trip is unnecessary, since the signal itself contains
the same information.
This changeset avoids this follow-up query, and drops the now-unused
`Setter`.
> Avoid a second query for the current color-scheme

- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/prepare/prepare.py
- snap/snapcraft.yaml
Downgrade pipewire headers as openal won't work with pipewire version less than headers it builds with now
> Update openal to 1.22.1

- Telegram/SourceFiles/window/themes/window_theme.cpp
- Telegram/SourceFiles/window/themes/window_theme.h
> Automatically reload theme on file change

- .github/workflows/winget.yml
@john-preston @ilya-fedin this PR adds beta releases too.
> WinGet: Publish beta releases also

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
> Add fail callback to linux notifications exceptions handler

- Telegram/SourceFiles/core/sandbox.cpp
- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/SourceFiles/platform/linux/linux_xdp_open_with_dialog.cpp
Depends on https://github.com/desktop-app/lib_base/pull/130
> Use xdg-activation to open URLs&files

- Telegram/SourceFiles/media/view/media_view_pip.cpp
- Telegram/SourceFiles/media/view/media_view_pip.h
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/203, https://github.com/desktop-app/lib_ui/pull/115
> Let PiP have custom buffer size on Wayland

- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
- Telegram/cmake/lib_tgvoip.cmake
- Telegram/cmake/telegram_options.cmake
- docs/building-linux.md
- docs/building-mac.md
- docs/building-win-x64.md
- docs/building-win.md
Depends on https://github.com/desktop-app/cmake_helpers/pull/208
> Use cmake_dependent_option to better declare variables that relate on other variables

- Telegram/SourceFiles/media/view/media_view_pip.cpp
It provides no difference, there was a mistake while testing the behavior
> Don't use QWindowSystemInterface in the PiP

- Telegram/SourceFiles/ffmpeg/ffmpeg_emoji.h
I also did the same with lottie, let me know if it was correct way to approach this.
> Fix build with GCC 12.

- snap/snapcraft.yaml
This should make webview working as well as auto-reconnection when system network changed
> Add missing network-status permission

- Telegram/SourceFiles/export/output/export_output_json.cpp
> Fix JSON output when exporting custom emojis

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
And patch to cache portal result
> Update kcoreaddons to 5.98.0

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Removing po folder from kcoreaddons allows that
> Avoid building qttools

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
De[ends on https://github.com/desktop-app/lib_base/pull/135
> Replace EscapeShell with KShell::joinArgs

- Telegram/SourceFiles/core/update_checker.cpp
- Telegram/SourceFiles/core/utils.h
- Telegram/SourceFiles/mtproto/session_private.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.h
- Telegram/SourceFiles/platform/linux/tray_linux.cpp
- Telegram/SourceFiles/platform/mac/specific_mac.h
- Telegram/SourceFiles/platform/platform_specific.h
- Telegram/SourceFiles/platform/win/specific_win.h
- Telegram/SourceFiles/settings/settings_codes.cpp
- Telegram/SourceFiles/stdafx.h
- Telegram/SourceFiles/window/main_window.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/224
> Use KSandbox to check flatpak/snap environment

- CMakeLists.txt
Depends on https://github.com/desktop-app/cmake_helpers/pull/227
> Implement target_compile_options_if_exists, target_link_options_if_exists

- Telegram/SourceFiles/passport/passport_panel_edit_scans.cpp
- Telegram/SourceFiles/passport/passport_panel_edit_scans.h
libc++ in newer llvm requre completely defined ScanListData
> fix clang15/libc++15 build

- Telegram/SourceFiles/media/view/media_view_pip.cpp
Surface size is buffer size, in fact...
> Fix the comment about surface size in media_view_pip

- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/SourceFiles/platform/linux/linux_xdp_open_with_dialog.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/build/docker/centos_env/Dockerfile
Depends on https://github.com/desktop-app/patches/pull/110, https://github.com/desktop-app/cmake_helpers/pull/239, https://github.com/desktop-app/lib_base/pull/138, https://github.com/desktop-app/lib_webview/pull/31
> Update glibmm to latest version

- Telegram/build/docker/centos_env/Dockerfile
Depends on https://github.com/desktop-app/cmake_helpers/pull/238
> Parallelize LTO on Linux

- Telegram/build/prepare/prepare.py
It has new signatures and fixes the CI
> Update msys2 base

- .gitmodules
Depends on https://github.com/desktop-app/cmake_helpers/pull/242, https://github.com/desktop-app/lib_spellcheck/pull/21
> Implement sonnet-based language detection backend

- .gitmodules
- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/244
> Add protobuf to snap

- .github/workflows/docker.yml
- Telegram/build/prepare/linux.sh
- docs/building-linux.md
This seem to work better with distribution-provided Docker
> Replace docker buildx with DOCKER_BUILDKIT=1 environment variable

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
> Fix build with Qt 5

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
It seems there's a race condition when Telegram is auto-started on Plasma and it doesn't hurt to issue the signal always, so just remove the check
> Don't check com.canonical.Unity for the counter

- Telegram/build/prepare/prepare.py
> AVIF, JPEG XL, HEIF support in Windows build

- Telegram/SourceFiles/boxes/about_box.cpp
- Telegram/SourceFiles/boxes/about_sponsored_box.cpp
- Telegram/SourceFiles/history/history_location_manager.cpp
- Telegram/SourceFiles/settings/settings_main.cpp
- Telegram/SourceFiles/ui/chat/attach/attach_bot_webview.cpp
This also reverts commit bb94507af12d475673da7ddbb9b29920765fad0f.
> Replace various QDesktopService::openUrl with File::OpenUrl for correct operation on Linux

- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/prepare/prepare.py
Depends on https://github.com/desktop-app/cmake_helpers/pull/249
> Enable ffmpeg dav1d support

- Telegram/SourceFiles/api/api_authorizations.cpp
- Telegram/SourceFiles/boxes/peers/edit_peer_invite_link.cpp
- Telegram/SourceFiles/calls/calls_box_controller.cpp
- Telegram/SourceFiles/calls/group/ui/calls_group_scheduled_labels.cpp
- Telegram/SourceFiles/core/application.cpp
- Telegram/SourceFiles/core/ui_integration.cpp
- Telegram/SourceFiles/core/ui_integration.h
- Telegram/SourceFiles/data/data_peer.cpp
- Telegram/SourceFiles/data/data_peer_values.cpp
- Telegram/SourceFiles/dialogs/ui/dialogs_layout.cpp
- Telegram/SourceFiles/history/history_inner_widget.cpp
- Telegram/SourceFiles/history/history_item.cpp
- Telegram/SourceFiles/history/view/history_view_bottom_info.cpp
- Telegram/SourceFiles/history/view/history_view_list_widget.cpp
- Telegram/SourceFiles/history/view/media/history_view_call.cpp
- Telegram/SourceFiles/lang/lang_keys.cpp
- Telegram/SourceFiles/media/player/media_player_widget.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
- Telegram/SourceFiles/settings.cpp
- Telegram/SourceFiles/settings.h
- Telegram/SourceFiles/support/support_helper.cpp
- Telegram/SourceFiles/ui/chat/group_call_bar.cpp
- Telegram/SourceFiles/ui/text/format_values.cpp
- Telegram/SourceFiles/ui/text/format_values.h
This allows to use platform-specific formatting functions
> cTimeFormat/cDateFormat -> QLocale::ShortFormat

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/117, https://github.com/desktop-app/cmake_helpers/pull/250
> Support ICCv4 with Little CMS on Linux

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/153
> Fix build with clang

- Telegram/build/setup.iss
- Add Copyright message with copyright autor styarting and ending yaer (current year) copyright 
- Add AppVerName (app name and version on top left in main window)
> Update Inno Setup script

- Telegram/Resources/langs/lang.strings
- Telegram/SourceFiles/boxes/download_path_box.cpp
- Telegram/SourceFiles/core/application.cpp
- Telegram/SourceFiles/core/application.h
- Telegram/SourceFiles/core/file_utilities.cpp
- Telegram/SourceFiles/settings/settings_chat.cpp
> Hide default download folder option if it's not available

- Telegram/build/prepare/prepare.py
> Fix build with various Windows locales

- Telegram/build/prepare/prepare.py
> Fix the check for Native Tools Command Prompt in prepare.py

- Telegram/build/prepare/prepare.py
So new databases are downloaded in case runtime updates and gets new repostiories
> Do pacman -Syu twice in prepare.py

- Telegram/SourceFiles/storage/localimageloader.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/133
> Implement lossless jpeg progression

- Telegram/Resources/langs/lang.strings
- Telegram/SourceFiles/data/data_cloud_file.cpp
- Telegram/SourceFiles/data/data_document.cpp
- Telegram/SourceFiles/passport/passport_form_controller.cpp
- Telegram/SourceFiles/storage/file_download.cpp
- Telegram/SourceFiles/storage/file_download.h
- Telegram/SourceFiles/storage/file_download_mtproto.cpp
- Telegram/SourceFiles/storage/file_download_web.cpp
- Telegram/SourceFiles/storage/streamed_file_downloader.cpp
..and uncomment the code for handling incorrect permissions
> Differ file download failure reasons

- Telegram/SourceFiles/settings/settings_main.cpp
> Present window's devicePixelRatio in the UI

- .github/workflows/mac.yml
- Telegram/SourceFiles/core/launcher.cpp
- Telegram/SourceFiles/data/data_emoji_statuses.cpp
- Telegram/SourceFiles/history/view/history_view_bottom_info.cpp
- Telegram/SourceFiles/history/view/reactions/history_view_reactions.cpp
- Telegram/SourceFiles/history/view/reactions/history_view_reactions_list.cpp
- Telegram/SourceFiles/platform/mac/launcher_mac.h
- Telegram/SourceFiles/platform/mac/launcher_mac.mm
- Telegram/SourceFiles/platform/mac/main_window_mac.mm
- Telegram/SourceFiles/platform/mac/specific_mac_p.mm
- Telegram/SourceFiles/settings/settings_main.cpp
- Telegram/SourceFiles/storage/localimageloader.cpp
- Telegram/cmake/lib_tgcalls.cmake
Depends on https://github.com/desktop-app/cmake_helpers/pull/253, https://github.com/desktop-app/lib_base/pull/157, https://github.com/desktop-app/lib_ui/pull/136
> Use QT_DEPRECATED_WARNINGS_SINCE

- Telegram/SourceFiles/boxes/peers/edit_peer_permissions_box.cpp
- Telegram/SourceFiles/history/view/history_view_list_widget.h
Fixed build with GCC 13.
Closes #25820.
> Fixed build with GCC 13

- Telegram/build/prepare/prepare.py
These are mostly security improvements.
> Upgrade libde265, libheif, libjxl in Windows build and improvement in HEIF plug-in

- Telegram/SourceFiles/core/launcher.cpp
- Telegram/SourceFiles/logs.cpp
- Telegram/SourceFiles/settings.h
> Fallback to other working directories in debug mode on Unix systems

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- lib/xdg/org.telegram.desktop.desktop
Just like other GApplciation actions
> Make the quit action lowercase

- Telegram/SourceFiles/core/launcher.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/142
> Try to remove Wayland blacklist again

- Telegram/SourceFiles/core/sandbox.cpp
> Tell QLocalSocket the socket is abstract

- Telegram/SourceFiles/media/system_media_controls_manager.cpp
- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/267, https://github.com/desktop-app/lib_base/pull/170
> Add cppgir dependencies to Dockerfile

- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/linux/integration_linux.cpp
- Telegram/SourceFiles/platform/linux/org.freedesktop.portal.Inhibit.xml
Fixes #26256
Depends on https://github.com/telegramdesktop/tdesktop/pull/26286, https://github.com/telegramdesktop/tdesktop/pull/26283
> Implement screen locker monitor on Linux

- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/prepare/prepare.py
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/266, https://github.com/desktop-app/lib_spellcheck/pull/24
> Get rid of qt5compat dependency

- Telegram/SourceFiles/platform/linux/integration_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/273
> Constify options in Linux screen locker monitor

- .github/workflows/winget.yml
* Fixes https://github.com/telegramdesktop/tdesktop/issues/26040
> Fix installer selection for winget-releaser

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/142
> Update Qt to 6.5.1 on Linux

- Telegram/SourceFiles/platform/linux/linux_wayland_integration.cpp
- Telegram/SourceFiles/platform/linux/linux_wayland_integration.h
Depends on https://github.com/desktop-app/lib_base/pull/174, https://github.com/desktop-app/lib_ui/pull/149
> Use new base_linux_wayland_utilities

- .gitmodules
- Telegram/CMakeLists.txt
- Telegram/SourceFiles/platform/linux/linux_wayland_integration.cpp
Depends on https://github.com/desktop-app/lib_base/pull/176, https://github.com/desktop-app/lib_ui/pull/150
> C++ify wl_registry

- Telegram/SourceFiles/media/view/media_view_pip.cpp
- Telegram/build/docker/centos_env/Dockerfile
Depends on https://github.com/desktop-app/patches/pull/143, https://github.com/desktop-app/lib_ui/pull/152
> Send mouse release event after startSystemMove/startSystemResize

- Telegram/cmake/generate_midl.cmake
Depends on https://github.com/desktop-app/cmake_helpers/pull/274
> Use ARGN where applicable

- CMakeLists.txt
- Telegram/cmake/generate_scheme.cmake
Depends on https://github.com/desktop-app/cmake_helpers/pull/277
> Always use Python3 cmake package instead of the Python one

- Telegram/build/docker/centos_env/Dockerfile
https://github.com/desktop-app/cmake_helpers/pull/280
> Enable control flow protection

- Telegram/SourceFiles/platform/linux/linux_wayland_integration.cpp
Depends on https://github.com/desktop-app/lib_base/pull/183, https://github.com/desktop-app/lib_ui/pull/154
> Ensure Wayland integration instance accessor doesn't leak

- Telegram/SourceFiles/_other/packer.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/284, https://github.com/desktop-app/codegen/pull/17
> Migrate from qt_static_plugins.cpp to the Qt6-pregenerated initializators 

- Telegram/SourceFiles/platform/linux/integration_linux.cpp
- Telegram/SourceFiles/platform/linux/linux_xdp_open_with_dialog.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/147, https://github.com/desktop-app/cmake_helpers/pull/286, https://github.com/desktop-app/lib_base/pull/186, https://github.com/desktop-app/lib_ui/pull/155
> Use new glibmm 2.78 API

- Telegram/SourceFiles/platform/linux/integration_linux.cpp
> Make a weak pointer for GApplication startup lambda

- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/300, https://github.com/desktop-app/lib_base/pull/193, https://github.com/desktop-app/lib_ui/pull/161
> Port AppLaunchContext to cppgir

- Telegram/SourceFiles/platform/linux/integration_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/302, https://github.com/desktop-app/lib_base/pull/196, https://github.com/desktop-app/lib_webview/pull/50
> Get optional string support in cppgir

- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/156
> Fullscreen hack for Windows 11 native resize

- Telegram/SourceFiles/core/sandbox.cpp
Depends on https://github.com/desktop-app/lib_base/pull/197, https://github.com/desktop-app/lib_ui/pull/165
> Use QEvent::registerEventType for custom event types

- Telegram/SourceFiles/core/launcher.cpp
This exclusion doesn't have sense since `#ifndef _DEBUG`
> Make the logging disabling logic more logical

- Telegram/SourceFiles/history/view/reactions/history_view_reactions_selector.cpp
- Telegram/SourceFiles/history/view/reactions/history_view_reactions_selector.h
- Telegram/SourceFiles/media/stories/media_stories_reactions.cpp
Extents is a synonym of size but we're setting not window size.
Depends on https://github.com/desktop-app/lib_ui/pull/167
> Fix window extents terminology

- Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp
Depends on https://github.com/desktop-app/lib_base/pull/199
> Re-use base_linux_library

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
All those dbus methods call callbacks on the same thread
> Don't use crl::on_main unnecessarily in Linux native notifications code

- Telegram/SourceFiles/platform/linux/linux_xdp_open_with_dialog.cpp
Depends on https://github.com/desktop-app/lib_base/pull/201
> Switch XDP open with dialog to QWaylandWindow::requestXdgActivationToken

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
That's what snapd's apparmor profiles use
> Use SNAP_INSTANCE_NAME in SingleInstanceLocalServerName

- Telegram/SourceFiles/platform/linux/integration_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/216, https://github.com/desktop-app/lib_ui/pull/173
> Make use of the new XDP::SettingWatcher constructor

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/217, https://github.com/desktop-app/lib_ui/pull/174
> Make use of templated XDP::ReadSetting

- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/SourceFiles/platform/linux/integration_linux.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/SourceFiles/platform/linux/specific_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/218
> Avoid unneeded std::string casts in exception handling

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
Depends on https://github.com/desktop-app/lib_spellcheck/pull/28
> Use Glib::ustring in Linux notification globals

- .github/workflows/linux.yml
- Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp
- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/build/docker/centos_env/Dockerfile
Depends on https://github.com/desktop-app/patches/pull/144, https://github.com/desktop-app/cmake_helpers/pull/285, https://github.com/desktop-app/lib_base/pull/184
> Changes for the July old system deprecation

- Telegram/Resources/langs/lang.strings
- Telegram/SourceFiles/settings/settings_advanced.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/176
> Add Qt window frame string for Wayland

- Telegram/SourceFiles/platform/win/notifications_manager_win.cpp
- Telegram/SourceFiles/platform/win/specific_win.cpp
- Telegram/SourceFiles/platform/win/windows_app_user_model_id.cpp
- Telegram/SourceFiles/platform/win/windows_app_user_model_id.h
- Telegram/SourceFiles/platform/win/windows_dlls.cpp
- Telegram/SourceFiles/platform/win/windows_dlls.h
> Always set AppUserModelID on Windows

- Telegram/SourceFiles/_other/packer.cpp
- Telegram/SourceFiles/_other/packer.h
- Telegram/SourceFiles/core/crash_reports.cpp
- Telegram/SourceFiles/core/crash_reports.h
- Telegram/SourceFiles/core/update_checker.cpp
- Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp
- Telegram/SourceFiles/platform/mac/specific_mac.mm
- Telegram/SourceFiles/platform/win/specific_win.cpp
- Telegram/SourceFiles/ui/controls/window_outdated_bar.cpp
- Telegram/SourceFiles/ui/controls/window_outdated_bar_dummy.cpp
- Telegram/cmake/td_ui.cmake
- Telegram/cmake/telegram_options.cmake
Depends on https://github.com/desktop-app/cmake_helpers/pull/313, https://github.com/desktop-app/lib_base/pull/220, https://github.com/desktop-app/lib_ui/pull/179, https://github.com/desktop-app/lib_lottie/pull/11
> Minimize amount of code to rebuild when switching options

- Telegram/SourceFiles/media/view/media_view_overlay_opengl.cpp
- Telegram/SourceFiles/platform/linux/linux_wayland_integration.cpp
Depends on https://github.com/desktop-app/lib_base/pull/222
> Support Wayland display reconnection

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/156
> Update Qt to 6.6.0-beta4 on Linux

- Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Telegram/SourceFiles/platform/linux/file_utilities_linux.h
Depends on https://github.com/desktop-app/lib_base/pull/221
> Patch Qt for better open url UX on Linux

- Telegram/SourceFiles/core/sandbox.cpp
This reverts commit 51027a0bc25e10e22244dedd0349ed939188f190.
Depends on https://github.com/desktop-app/lib_ui/pull/181
> Revert "Workaround Wayland popup menu bug."

- Telegram/build/docker/centos_env/Dockerfile
> Disable vfork in Qt on Linux

- snap/snapcraft.yaml
> Add libnvidia-egl-wayland1 to snap

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
> Downgrade qtwayland to 6.5.3

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/159
> Update to Qt 6.6.0 release on Linux

- Telegram/SourceFiles/platform/win/integration_win.cpp
- Telegram/SourceFiles/platform/win/main_window_win.cpp
- Telegram/SourceFiles/platform/win/tray_win.cpp
- Telegram/SourceFiles/platform/win/tray_win.h
> Implement monochrome tray icon on Windows

- Telegram/SourceFiles/core/sandbox.cpp
- Telegram/SourceFiles/core/sandbox.h
- Telegram/SourceFiles/settings/settings_experimental.cpp
- Telegram/SourceFiles/settings/settings_notifications.cpp
- Telegram/SourceFiles/window/notifications_manager_default.cpp
- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/prepare/prepare.py
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/161, https://github.com/desktop-app/lib_ui/pull/188
> Force enable fractional-scale-v1 experimental option

- Telegram/build/docker/centos_env/Dockerfile
Depends on #27157
Fixes #27123
> Update xkbcommon in Docker

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
> Build GLib manually in Docker and Snap

- Telegram/SourceFiles/core/sandbox.cpp
- Telegram/build/docker/centos_env/Dockerfile
> Fix remaining known xdg-output fractional scaling issues on Wayland 

- Telegram/SourceFiles/payments/ui/payments_panel.cpp
- Telegram/SourceFiles/payments/ui/payments_panel.h
- Telegram/SourceFiles/ui/chat/attach/attach_bot_webview.cpp
Depends on https://github.com/desktop-app/lib_webview/pull/67
> Handle webview crash

- Telegram/SourceFiles/platform/linux/integration_linux.cpp
- Telegram/SourceFiles/platform/linux/launcher_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/325, https://github.com/desktop-app/lib_base/pull/233, https://github.com/desktop-app/lib_webview/pull/68
> Update to the new cppgir API

- Telegram/SourceFiles/core/sandbox.cpp
- Telegram/SourceFiles/core/sandbox.h
- Telegram/SourceFiles/settings/settings_experimental.cpp
- Telegram/build/docker/centos_env/Dockerfile
Depends on https://github.com/desktop-app/patches/pull/168
> Revert "Force enable fractional-scale-v1 experimental option"

- Telegram/SourceFiles/payments/ui/payments_panel.cpp
- Telegram/SourceFiles/ui/chat/attach/attach_bot_webview.cpp
> Check whether webview is destructed after Webview::Window::init

- .github/workflows/linux.yml
- Telegram/build/docker/centos_env/build.sh
- docs/building-linux.md
Default to RelWithDebInfo for both optimizations and debug information
> Let specify arbitrary build configuration via Docker

- Telegram/configure.py
Removing variables that make no sense
> Remove duplicates from configure.py

- Telegram/SourceFiles/platform/linux/specific_linux.cpp
> Ensure custom arguments get applied in generated .desktop file

- Telegram/build/docker/centos_env/Dockerfile
Depends on https://github.com/desktop-app/patches/pull/179, https://github.com/desktop-app/cmake_helpers/pull/330
> Switch from libproxy to GProxyResolver

- Telegram/SourceFiles/history/view/media/history_view_photo.cpp
> Fix a std::clamp assertion

- Telegram/build/setup.iss
before:
https://ibb.co/pZTX1QH
after:
https://ibb.co/593yhwp
> use modern installer style

- Telegram/build/prepare/prepare.py
update new script location in qt repo
https://github.com/qt/qt5/commit/1971e8075d8f55256bfbd38b28165b47d3cf8cff
> Fix libraries build (qt5)

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/183, https://github.com/desktop-app/cmake_helpers/pull/337
> Update Qt to 6.7.0 on Linux

- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> Fix media viewer geometry restoration

- Telegram/build/prepare/prepare.py
I updated these libraries because they contains various fixes for discovered bugs/vulnerabilities.
I tested local build on Windows.
> Upgrade dav1d, libavif, libde265, libheif

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/339
> Move OpenSSL to system directories on Linux

- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
- Telegram/SourceFiles/media/view/media_view_pip.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/206
> Let Wayland to use QGuiApplication::screenAt

- Telegram/build/docker/centos_env/Dockerfile
Depends on https://github.com/desktop-app/cmake_helpers/pull/344
> Install protobuf in Docker

- Telegram/build/docker/centos_env/Dockerfile
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/345
> Replace mozjpeg with jpegli on Linux

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
> Remove XCBSetDesktopFileName

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
> Revert "Remove not really needed notification capability checks"

- .github/workflows/cant-reproduce.yml
- .github/workflows/needs-user-action.yml
- .github/workflows/waiting-for-answer.yml
> Schedule no-response action runs at different times

- Telegram/SourceFiles/ffmpeg/ffmpeg_frame_generator.cpp
- Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp
- Telegram/SourceFiles/ffmpeg/ffmpeg_utility.h
- Telegram/SourceFiles/media/audio/media_audio_capture.cpp
- Telegram/SourceFiles/media/clip/media_clip_ffmpeg.cpp
avio: Constify data pointees of write callbacks
Ref: https://github.com/FFmpeg/FFmpeg/commit/2a68d945cd74265bb71c3d38b7a2e7f7d7e87be5
https://github.com/FFmpeg/FFmpeg/commit/02aea61d69d8f81bc285e2131bf25f96a3e27feb
> Add compatibility with FFMPEG 7.0

- Telegram/SourceFiles/dialogs/dialogs_widget.cpp
- Telegram/SourceFiles/dialogs/dialogs_widget.h
> Forward input method event from Dialogs::Widget to search field

- Telegram/SourceFiles/dialogs/dialogs_widget.cpp
> Remove unneeded Qt::WA_InputMethodEnabled

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
Depends on https://github.com/desktop-app/lib_base/pull/251, https://github.com/desktop-app/lib_ui/pull/223
> Remove std::optional indrection for nullable XCB types

- Telegram/SourceFiles/calls/group/calls_group_panel.cpp
- Telegram/SourceFiles/dialogs/dialogs_widget.cpp
- Telegram/SourceFiles/dialogs/ui/dialogs_stories_list.cpp
- Telegram/SourceFiles/dialogs/ui/dialogs_stories_list.h
- Telegram/SourceFiles/history/history_widget.cpp
- Telegram/SourceFiles/iv/iv_controller.cpp
- Telegram/SourceFiles/mainwindow.cpp
- Telegram/SourceFiles/media/stories/media_stories_controller.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
- Telegram/SourceFiles/window/main_window.cpp
- Telegram/SourceFiles/window/main_window.h
Depends on https://github.com/desktop-app/lib_ui/pull/225
> Use less QWindow signals

- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> Ensure media viewer has native window handle before using it

- Telegram/SourceFiles/calls/group/ui/desktop_capture_choose_source.cpp
- Telegram/SourceFiles/dialogs/dialogs_widget.cpp
- Telegram/SourceFiles/history/view/history_view_top_bar_widget.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_widget.h
- Telegram/SourceFiles/media/view/media_view_pip.cpp
- Telegram/SourceFiles/media/view/media_view_pip.h
- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/linux/main_window_linux.h
- Telegram/SourceFiles/window/main_window.cpp
- Telegram/SourceFiles/window/notifications_manager_default.cpp
- Telegram/SourceFiles/window/window_connecting_widget.cpp
- Telegram/SourceFiles/window/window_connecting_widget.h
- Telegram/SourceFiles/window/window_main_menu.cpp
- Telegram/build/qt_version.py
- Telegram/configure.py
Depends on https://github.com/desktop-app/lib_ui/pull/227
> Use less QWindow events

- Telegram/SourceFiles/platform/linux/main_window_linux.cpp
- Telegram/SourceFiles/platform/mac/main_window_mac.mm
> Set shortcut context for global menu shortcuts

- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> Query QWindow::windowState in media viewer

- Telegram/SourceFiles/media/view/media_view_pip.cpp
> Delay clearing transient parent until the pip window is really exposed

- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/docker/centos_env/build.sh
Depends on https://github.com/desktop-app/cmake_helpers/pull/357
> Get release CFLAGS from Dockerfile on Linux

- Telegram/SourceFiles/calls/calls_panel.cpp
- Telegram/SourceFiles/calls/group/calls_group_panel.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/236
> Add hit test for window context menu

- Telegram/CMakeLists.txt
Depends on https://github.com/desktop-app/cmake_helpers/pull/359
> Use CMAKE_CXX_COMPILER_FRONTEND_VARIANT

- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
- Telegram/SourceFiles/platform/win/integration_win.cpp
Depends on https://github.com/desktop-app/patches/pull/205, https://github.com/desktop-app/lib_ui/pull/239
> Qt6 viewer fix

- Telegram/SourceFiles/calls/calls.style
- Telegram/SourceFiles/calls/calls_panel.cpp
- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
- Telegram/SourceFiles/platform/platform_overlay_widget.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/243
> One side controls

- .gitmodules
Depends on https://github.com/desktop-app/cmake_helpers/pull/320
> Update GSL to 4.1.0

- Telegram/SourceFiles/dialogs/dialogs_widget.cpp
- Telegram/SourceFiles/settings/settings_folders.cpp
- Telegram/SourceFiles/window/main_window.cpp
- Telegram/SourceFiles/window/window_controller.cpp
- Telegram/SourceFiles/window/window_session_controller.cpp
- Telegram/SourceFiles/window/window_session_controller.h
Turn them into horizontal automatically instead
> Don't expand minimum window size for folders

- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/prepare/prepare.py
- Telegram/build/qt_version.py
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/218
> Update Qt 6.8.0 -> 6.8.1

- README.md
Update name of "Vazirmatn" project.
> Update from 'vazir' to 'vazirmatn'

- Telegram/SourceFiles/mtproto/session_private.cpp
- Telegram/SourceFiles/mtproto/session_private.h
- Telegram/SourceFiles/settings/settings_experimental.cpp
> Added experimental settings to prefer ipv6 when it is available

- Telegram/SourceFiles/calls/group/calls_group_panel.cpp
- Telegram/SourceFiles/media/view/media_view_pip.cpp
- Telegram/SourceFiles/platform/platform_overlay_widget.cpp
Depends on https://github.com/desktop-app/lib_ui/pull/250
> Adapt to TitleControlsLayout change

- Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
Fixes https://github.com/telegramdesktop/tdesktop/issues/28981
> Video Player: Fix caption elements being clickable in video fullscreen

- Telegram/SourceFiles/platform/win/file_utilities_win.cpp
**Problem:**
Telegram Desktop on Windows does not respect the system policy "Do not preserve zone information in file attachments". As a result, even when this policy is enabled, an NTFS alternate data stream (`Zone.Identifier:$DATA`) is still created for every downloaded file.
**Solution:**
This change ensures that the Zone.Identifier stream is not created when the system policy explicitly restricts this behavior, aligning Telegram Desktop's behavior with Windows security settings.
> Respect "Do not preserve zone information in file attachments" policy on Windows

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
Looks like it was broken since addition
> Fix clearFromTopic on Linux

- Telegram/build/prepare/prepare.py
Depends on https://github.com/desktop-app/cmake_helpers/pull/376
> Add lcms2 dependency for Qt6 on Windows

- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/prepare/prepare.py
- Telegram/build/qt_version.py
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/223, https://github.com/desktop-app/lib_base/pull/268
> Update Qt 6.8.2 -> 6.9.0

- Telegram/SourceFiles/core/file_utilities.cpp
This allows it to have all supported image extensions just like ImagesFilter
> Use Ui::ImageExtensions in PhotoVideoFilesFilter

- Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
> Fix a crash on Linux without actions notification capability

- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/prepare/prepare.py
- snap/snapcraft.yaml
Updates ada-url to latest version.
cc @john-preston
> update ada-url to v3.2.2

- .github/workflows/mac_packaged.yml
- Telegram/CMakeLists.txt
- Telegram/build/docker/centos_env/Dockerfile
- Telegram/cmake/lib_tgcalls.cmake
- Telegram/cmake/lib_tgvoip.cmake
- Telegram/cmake/td_ui.cmake
Depends on https://github.com/desktop-app/cmake_helpers/pull/379
> cmake fixes

- CMakeLists.txt
> Raise minimum required cmake version to 3.25

- Telegram/SourceFiles/core/file_utilities.cpp
> Return accidentally removed video formats

- .github/workflows/mac_packaged.yml
- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/prepare/prepare.py
- Telegram/cmake/td_tde2e.cmake
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/cmake_helpers/pull/396
> td -> tde2e

- Telegram/build/docker/centos_env/Dockerfile
> Use Python 3.12 in Docker

- .github/workflows/linux.yml
- Telegram/SourceFiles/_other/updater_linux.cpp
- Telegram/build/docker/centos_env/Dockerfile
- Telegram/build/docker/centos_env/build.sh
- Telegram/build/qt_version.py
- docs/building-linux.md
- snap/snapcraft.yaml
Depends on https://github.com/desktop-app/patches/pull/226, https://github.com/desktop-app/cmake_helpers/pull/401, https://github.com/desktop-app/lib_base/pull/270
> Update GCC to 14 on Linux

- Telegram/build/docker/centos_env/Dockerfile
> Fix default cursor path

- .gitmodules
- Telegram/SourceFiles/platform/linux/integration_linux.cpp
Depends on https://github.com/desktop-app/cmake_helpers/pull/417
> Limit the amount of malloc arenas and call malloc_trim periodically with glibc
