Telegram/SourceFiles/stdafx.cpp, Telegram/Telegram.pro
Qt5 supported ibus offcially, I add symbols to telegram's static build,
=> Add Ibus supported by Qt5 officially

Telegram/SourceFiles/application.cpp, Telegram/SourceFiles/application.h, Telegram/SourceFiles/autoupdater.cpp, Telegram/SourceFiles/autoupdater.h, Telegram/SourceFiles/intro/intro.cpp, Telegram/SourceFiles/main.cpp, Telegram/SourceFiles/mainwidget.cpp, Telegram/SourceFiles/settingswidget.cpp, Telegram/SourceFiles/settingswidget.h, Telegram/SourceFiles/sysbuttons.cpp, Telegram/SourceFiles/title.cpp
Adding "DEFINES += TDESKTOP_DISABLE_AUTOUPDATE" to Telegram.pro would disable the updater. This eases creating packages for Linux distributions, where updates are handled by the corresponding package manager.
=> Allow to disable the updater using a marco

Telegram/SourceFiles/pspecific_linux.cpp, Telegram/SourceFiles/pspecific_mac_p.mm, Telegram/SourceFiles/pspecific_wnd.cpp
Adding "DEFINES += TDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME" to Telegram.pro would disable these functions. This can be useful when the application is distributed using an installer or a package manager that can apply these settings system-globaly.
=> Allow to disable 'register custom scheme' functions using a macro

MSVC.md
The command "pacman -S mingw64/mingw-w64-x86_64-opus" gives an error and based on the comment on this ticket: http://sourceforge.net/p/msys2/tickets/186/ , we should sync the package database first.
It worked for me.
=> Resolving "failed retrieving file" error

Telegram/_qt_5_5_0_patch/qtbase/src/widgets/widgets/qwidgettextcontrol.cpp
A quick hotfix for issue #1176. 
This may also fix any other issues with the key combination which are raised because of stripped Ctrl+ and Ctrl+Shift+ in Qt code.
=> Fixed issue 1176

Telegram/Telegram.pro
It is needed to use UTF-16 string literals (u"string"), which are generated by MetaLang.
=> Add c++11 config flag to Telegram.pro

Telegram/SourceFiles/autoupdater.cpp, Telegram/SourceFiles/autoupdater.h
It is needed by boxes/aboutbox.cpp.
=> Build function countBetaVersionSignature() when autoupdater is disabled

Telegram/SourceFiles/logs.cpp
it seems telegram overwrites my `-workdir` argument in `logsInit`, ref #297 
here is a simple fix for that
=> force telegram respoect my workdir settings

Telegram/SourceFiles/autoupdater.cpp, Telegram/SourceFiles/autoupdater.h
If the 'TDESKTOP_DISABLE_AUTOUPDATE' defined, a build is failing because empty moc_autoupdater.cpp is being generated and the msvc compiler will complain about 'stdafx.h not found'. In addition, aboutbox.cpp also refers to countBetaVersionSignature() which will not be included when TDESKTOP_DISABLE_AUTOUPDATE defined.
Added a dummy UpdateDownloader inherits QObject when TDESKTOP_DISABLE_AUTOUPDATE not defined, and moved the location of countBetaVersionSignature(uint64 version) to outside of #ifndef/endif scope.
Fixed & Tested on dev branch w/ VS2015.
=> Fix a build error when TDESKTOP_DISABLE_AUTOUPDATE preprocessor defined.

Telegram/SourceFiles/pspecific_linux.cpp
Put the icon file in .local/share/icons/ to let the user's theme get the upper hand (ex: default kde icons theme)
=> Use linux icon theme

CONTRIBUTING.md
It's better to rebase a pull request instead of merging the latest commits
=> Rebase instead of merge

lib/xdg/telegramdesktop.desktop, lib/xdg/tg.protocol
Include a .desktop file (for app menu in xdg-complaint desktops), and tg.protocol (for having xdg-complaint apps pick up the tg: protocol).
The intention of including these files is for package maintainers to re-use them, instead of each or them re-writing (or re-bundling for somewhere else) these files.
=> Include some reference XDG files

Telegram/SourceFiles/boxes/confirmbox.cpp
It seems that `Notify all members` checkbox was inverted.
I'm talking about this one:
If I set it to `unchecked`, other supergroup members say they recieved notification, but when I leave it `checked` — they hadn't recieved anything. 
As you can see in source, `silent` flag was used when checkbox was checked, but text of the checkbox is about notification, not about silence :)
=> Fixed inverted checkbox for notify members about pinned message

lib/xdg/telegramdesktop.desktop
x-xdg-protocol has never been a way to bind to a schema in XDG.
=> Remove nonexistant MIME type from desktop file

.travis/build.sh
breakpad is still broken
```
Build breakpad
.travis/build.sh: line 111: cd: /build/Libraries/breakpad: No such file or directory
+ cd qtbase
+ /build/qt5_6_0/qtbase/configure -top-level 
Which edition of Qt do you want to use ?
Type 'c' if you want to use the Commercial Edition.
Type 'o' if you want to use the Open Source Edition.
```
=> Fix path to qt patch

doc/building-msvc.md
* Use depot_tools to prepare breakpad instead of invoking gyp directly--fixes missing directory error
* Formatting consistency
* Help for common errors
* Use `/Zi` instead of `/ZI` for building openal-soft--fixes flag conflict for Debug configuration
=> Updates/fixes for Windows build instructions

Telegram/Telegram.pro
Fixes a race when `make` is running in multiprocess mode with the flag `-j`, but files that are produced by `codegen_style`, have not exist yet. A build fails if the compilation of `Telegram` are started when `codegen_style` has not been finished.
Also the automatically generated code will be created in the release build.
=> Repair of parallel build; reconstruction of release build of satellites

.travis.yml, .travis/build.sh, Telegram/SourceFiles/pspecific_linux.cpp
The two elements I've stripped out (runtime-generated `.desktop` launcher and xdg mime URI association) are in my view at best redundant functions and at worst meddling gremlins in the machinery.
Packagers who previously relied on the generated-at-launch `.desktop` file should instead use the one provided in `lib/xdg/`, modifying if necessary.
Fixes #306
=> strip out .desktop file generation (and xdg uri association)

.travis.yml
> Now, a build will finish as soon as a job has failed, or when the only jobs left allow failures.
See https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing
=> Add fast finish to travis

.travis.yml, .travis/check.sh
With this PR, travis will add a comment to all PR's which have a commit which is missing the signature.
**Depends on #2210 and #2213 (merge first!)**
=> Automatic comment for missing signatures

.travis/build.sh, Telegram/Telegram.pro, Telegram/build/build.sh, Telegram/build/makefile_static.sh, doc/building-qmake.md
Hi,
This PR replaces hard-coded paths in `Telegram.pro` with [`pkg-config`](https://en.wikipedia.org/wiki/Pkg-config) invocation. All remaining `/usr/local/` references (which usually don't present on user system) are moved to `build/build.sh`, so that `Telegram.pro` is now generic and should work on any system without patching paths.
=> Replace hard-coded paths with pkg-config

Telegram/SourceFiles/mediaview.cpp, Telegram/SourceFiles/mediaview.h
Hello!
In many standard image viewers mouse wheel uses for zoom in/zoom out.
This is more convenient than Ctrl+Plus/Ctrl+Minus/Ctrl+0.
Fix #1013
=> Add zooming in media viewer on mouse wheel

doc/building-msvc.md
The issue is that Markdown parser doesn't handle code blocks after lists right. Instead of putting code into a block, it is shown as regular unformatted text. To resolve this issue, the empty HTML comments were added between lists and code blocks.
Signed-off-by: Sergey Filatov <raxp.worm202@gmail.com> (github: worm202)
=> Fixed Markdown parsing issues in build documentation for Windows

Telegram/gyp/refresh.sh
Old pull: #2650  
If this script is executed as `./refresh.sh` instead of bash `./refresh.sh` you may recieve the error:  
>./refresh.sh: 3: ./refresh.sh: pushd: not found  
This fixes the issue by making sure that bash is always used (as pushd is a bash extension).
=> Fixes "pushd: not found"

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
As per [freedesktop specifications](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html), $XDG_CURRENT_DESKTOP is a "colon-separated list of strings". Thus we need to parse it in that way.
Various desktops are now exporting this variable exposing multiple flavors.
=> main-window-linux: parse XDG_CURRENT_DESKTOP as colon separated list

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
AppIndicator is the native format for indicators in Ubuntu unity shell, since telegram supports them, it's better to rely on the system library for that. As it also allows better integration with [snap packages](http://snapcraft.io).
This PR has https://github.com/telegramdesktop/tdesktop/pull/2659 as prerequisite.
=> main-window-linux: try to use AppIndicator in Unity

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
There were some missing unref's around in the linux main window
=> main-window-linux: unref tray Indicator and Unity Launcher Entry

Telegram/SourceFiles/historywidget.cpp
error: inconsistent deduction for 'auto': 'int' and then 'auto'
auto start = 0, end = list.size();
^~~~
=> Fix compilation of history widget.

Telegram/SourceFiles/core/click_handler_types.cpp
Adds support for telegram.dog links
Matches:
* t.me
* telegram.me
* telegram.dog
But not `t.dog`.
=> Update regex (Fix #3111)

Telegram/SourceFiles/core/click_handler_types.cpp
Before, this regex matched also links which contained a in app link, e.g.: https://github.com/search?q=https://telegram.me/BotFather
Fix #3141
=> Fix regex for in app links

Telegram/SourceFiles/platform/linux/specific_linux.cpp, lib/xdg/telegramdesktop.desktop
What I have done:
* Removed deprecated _Encoding_ key
* Specified correct WM class for _StartupWMClass key_
* Fixed icon name in `lib/xdg/telegramdesktop.desktop`
The _Encoding_ key is deprecated as [the specification says][1].
A WM class, which was specified, represents the name of binary and depends on its file name. Qt sets this class equal to the _ApplicationName_, which you specified in [Telegram/SourceFiles/main.cpp][2]. To show all WM classes use **xprop** utility.
What happens if you specify incorrect _StartupWMClass_: then when you click on Telegram menu item, you'll see two Telegram icon on the taskbar. And one of them will disappear after a while.
---
I also fixed restarting when language is changed and there is no Updater near Telegram executable file. By the way, you need not …
=> Update .desktop file on Linux

.travis/build.sh
Signed-off-by: Fritz Elfert <fritz-github@fritz-elfert.de> (github: felfert)
When attempting to build on my own travis account, those two changes were necessary, because I did not yet had dependencies cached and therefore full builds were necessary.
- The libva repo has moved.
- The invocation of the init-repository script in the Qt repo has changed.
=> Update libva git URL and QT init-repository invocation

lib/xdg/telegramdesktop.appdata.xml
Add appstream metadata file [1] providing basic information about telegram desktop app. I would also prefer if there is some official screenshot rather than the one I'm currently hosting, but that can be changed later. The most important thing is to agree on appstream app ID, which can be then used to identify telegram desktop app, e.g. when writing reviews in ODRS [2].
[1] - https://www.freedesktop.org/wiki/Distributions/AppStream/
[2] - https://odrs.gnome.org/
=> Add appstream metadata file

Telegram/SourceFiles/window/themes/window_theme_preview.cpp
Time on theme preview is not consistent. There is a difference between time in dialog list and time of last message in current dialog. Besides, I doubt that an interlocutor, Eva Summer, can answer immediately, without any delay.
This commit fixes these contradictions.
=> Make theme preview more realistic

Telegram/SourceFiles/window/window_main_menu.cpp
To be honest, I am not very familiar with TDesktop code and I didn't know how to check if user is forwarding some messages. But the patch works correctly without that check.
=> Fix canceling forward when clicking on _userpicButton or _cloudButton

.github/ISSUE_TEMPLATE.md
Those \*\*Logs\*\* instead of <b>Logs</b> make me sad :c
=> Fix markdown in issue template

Telegram/Resources/basic.style
Full-width text-only messages are slightly wider than images.
=> Fix inconsistency of max width for message content

Telegram/SourceFiles/profile/profile_block_group_members.cpp
If user invites X to group and then X becomes an admin, user won't be able to remove X anymore, so remove option shouldn't be shown.
Currently remove is always shown if X was invited by user.
=> Fix remove option in normal groups

Telegram/gyp/telegram_mac.gypi
If ld finds ssl/crypto dylibs it prefers them to static archived objects
And because of that produced .app links dynamically to openssl, so it
won't launch unless users install openssl.
There are two solutions: either uninstall openssl completely from build
machine on each build, or use paths to .a files.
Obviously latter is preferred.
See #3561 and #3635
=> Fix openssl ldflags on macOS

Telegram/Resources/langs/lang.strings, Telegram/SourceFiles/boxes/boxes.style, Telegram/SourceFiles/boxes/mute_settings_box.cpp, Telegram/SourceFiles/boxes/mute_settings_box.h, Telegram/SourceFiles/mainwidget.cpp, Telegram/SourceFiles/mainwidget.h, Telegram/gyp/telegram_sources.txt
Now, an user can choose silent time for a specific chat using Telegram Desktop, like on mobile platforms. The pop-up window may be caused by context menu of dialog list, and it is as follows.
=> Menu for picking mute time for specific chat

Telegram/Resources/langs/lang.strings
This is consistent with the Android version, and is more clear.
Also, in languages that use singular for all numbers, it avoids confusion between "3 people are typing" and "a person named '3' is typing".
=> Improve multiple people typing/playing message

.appveyor/install.bat
It will now try to clone the dependencies again, if there was a error while cloning them.
Happened for example [here](https://ci.appveyor.com/project/telegramdesktop/tdesktop/build/1.1.546_travis_fix/job/3cjpyph2320y2bdb).
=> Retry cloning dependencies if prebare.bat is missing

docs/building-msvc.md
Fixed 'change directory' commands for following build process step-by-step.
Re-opened as new to cull a number of previous erroneous commits in proposed branch.
=> Fix build instructions for MSVC

Telegram/SourceFiles/mainwindow.cpp
Notice how the words were duplicated right after the "Connecting..." message disappeared.
I think this bug is somehow related to the deletion of `ConnectingWidget` (or `QWidget`).
I was able to fix it by only hiding it instead.
**Operating system:** Windows 10 x64
=> Fix IME being interrupted after reconnection

Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp, Telegram/gyp/qt.gypi
Starting with Ubuntu 17.10 the interface will be provided by an
extension (shipped by default):
https://github.com/ubuntu/gnome-shell-extension-appindicator
Legacy tray icons have been completely removed in GNOME 3.26. By
checking the interface, this will allow users of other distributions
with GNOME to also use Telegram's indicator with the extension.
I have tested the Qt code snippet (it correctly detects if the extension is enabled), but couldn't test it with Telegram, as setting up the build environment seems to require Ubuntu 12.04 (and I'm running Fedora).
Previous PR: #3928
=> Prefer AppIndicator if DBus interface is available

.appveyor/install.bat
This is a very simple change that allow people to build Telegram like AppVeyor does it, but not in C:\TBuild (often C is "System Reserved" and cannot be used). Instead you can build it anywhere (from the visual studio 2017 x86 command prompt) like this:
>set BUILD_DIR=%CD%
>git clone https://github.com/telegramdesktop/tdesktop.git
>cd tdesktop
>.\.appveyor\install.bat
>msbuild Telegram\Telegram.sln /property:Configuration=Debug /p:Platform=Win32
Some notes:
- I replaced all C:\TBuild with %BUILD_DIR%, even if it is decided not to merge this, keep that.
- %BUILD_DIR%\Libraries\prepare.bat might fail to extract the 7z Qt libraries for some reason (even if 7z.exe is in PATH) this has not been fixed
=> allow a customized BUILD_DIR in install.bat

Telegram/SourceFiles/settings.h
Set 700 permisson on dir on every start.
Should fix #2666
=> Fix CVE-2016-10351: Insecure cWorkingDir permissions.

Telegram/SourceFiles/codegen/style/generator.cpp
As the title say, this is just a little edit in order to improve the readability of headers generated by codegen_style.
=> Avoid generating multiple time the forward declarations in the headers generated by codegen_style.

Telegram/SourceFiles/codegen/style/generator.cpp
Now Telegram Desktop could be built if a path to the source directory contains dashes.
For example, `C:\my-sources\Telegram`
Without that fix, codegen assumes, for example, that `C:\my` is a path to the image, and `sources\Telegram\someimage` is a modifier.
=> Fix handling of dashes in the style directory path

docs/building-xcode.md
Current instructions won't work if followed blindly. Also, there is a fix for xcode-select using the wrong binaries.
=> Fix build instructions

Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp, Telegram/SourceFiles/platform/linux/linux_desktop_environment.h
In Ubuntu (running in GNOME) we support AppIndicator's and
Launcher counters still.
=> linux-desktop-environment: detect Ubuntu properly enabling features

Telegram/SourceFiles/platform/linux/specific_linux.cpp
It could be different in confined environments.
Reading this from `passwd` isn't always reliable.
=> linux: use $HOME to determine actual user path

Telegram/SourceFiles/chat_helpers/emoji_suggestions_widget.cpp
All this patch does is to allow emojis beeing suggested - even if their names were spelled using uppercase letters.
As mentioned in #3985 and in #3748 it can happen
that users of a non-US keyboard type the emoji's name
in uppercase letters because the fastest way of typing e.g. `:relaxed:` involves using the
[Shift] key, which can lead (due to fast/bad typing) to writing the first
letters of the emoji's name in capitals. Telegram does currently not come up
with a suggestion at this point and one is forced to correct the first few letters - making
it quite inconvenient.
This patch should not be in conflict with anything. Also, the emoji names used are case-insensitive. (Meaning that there cannot be a "wrong" suggestion due to this patch)
This closes #3985 and partially resolves #3748 …
=> Let emoji suggestions be case insensitive

Telegram/gyp/linux_glibc_wraps.gyp, Telegram/gyp/settings_linux.gypi
This is required because uname -p actually returns "unknown" for some hardware. The uname help documents this by stating that -p is non-portable. The -m flag is the one to use.
=> Fix wrong uname flag used

Telegram/gyp/lib_export.gyp
Fixes the build failures locally (and hopefully) in travis
=> lib_export: use includes paths as defined per platform

Telegram/SourceFiles/base/bytes.h
This is required for gsl::span.
=> Add missing include to <gsl/gsl>

Telegram/SourceFiles/platform/linux/specific_linux.cpp
Closes: https://github.com/telegramdesktop/tdesktop/issues/5118
Signed-off-by: Henning Schild <henning@hennsch.de>
=> Linux: disable RegisterCustomScheme when internal updater is disabled

Telegram/SourceFiles/chat_helpers/emoji_list_widget.cpp, Telegram/SourceFiles/chat_helpers/emoji_list_widget.h
@john-preston 
Hi, this pull request adds a tooltip to the emojis, that shows the replacement text to type in when using the keyboard. This feature was requested by multiple users.
Of course this is entirely disabled, if the user disables "Suggest Emoji Replacements".
I use the `GetAllReplacements()` list to find the replacement text, if you know a better or faster way to get it, I am happy to incorporate that. :)
I hope I followed all your guidelines, if not feel free to point out any changes.
=> Show Emoji replacement tooltip on hover

Telegram/SourceFiles/platform/linux/specific_linux.cpp, lib/xdg/telegramdesktop.desktop, snap/snapcraft.yaml
Reduce the snap size by not providing themes, and fix installation of desktop and icon.
Also, added desktop keywords for all the platforms.
=> snap: fix building and use content-interfaces for assets

Telegram/SourceFiles/ui/widgets/input_fields.cpp
These variables, according to commit history, were added about two years ago and have never been used, so they can be safely removed.
=> Removed unused variables in input_fields.cpp.

Telegram/SourceFiles/platform/linux/linux_libs.cpp, Telegram/SourceFiles/platform/linux/linux_libs.h, Telegram/gyp/telegram_linux.gypi
Ayatana AppIndicator is a fork of Canonical's AppIndicator maintained by Debian community.
More info: https://lists.debian.org/debian-devel/2018/03/msg00506.html
=> Switch to Ayatana Indicators

Telegram/SourceFiles/data/data_document.cpp, Telegram/SourceFiles/overview/overview_layout.cpp
This PR fixes display of files with "audio/" MIME in Shared Media.
`DocumentData::isAudioFile()` checks the MIME, which leads to incorrect display of files involved in the audio.
Ordinary playlist files, such as m3u, are perceived by Telegram as playable files. After click on this file, Telegram tries to play it, but gets fail.
As far as I understand, Telegram does not need to check the "audio/" MIME at all, since file type is received from the server; even if the mp3 file is without an extension, it will still play perfectly and will be placed in "Audio files" category.
So, we have to remove `_mimeString.startsWith(qstr("audio/"), Qt::CaseInsensitive);`, but then `isAudioFile()` will return true only in one case, when `isSong()` is true. And we can safely combine `isSong()` and …
=> Fixed display of files with 'audio/' MIME in Shared Media.

Telegram/SourceFiles/history/history.cpp
This small PR fixes an issue that has been around for a long time.
Use case: if the user sends a message, then sends sticker, and then presses the KeyUp, the message editing does not work. The same goes for video-messages and call-messages.
Here's an illustration. Client on the left is before patch, client on the right is after patch.
=> Fixed editing of the last message on KeyUp.

Telegram/SourceFiles/mediaview.cpp
`MediaView::keyPressEvent` method has huge unnecessary condition at the last `} else if ` step. 
It completely repeats all terms of internal conditions and makes the expression more complicated and less readable.
All enumeration of conditions on 2490 line can be safely removed, just leave the `Qt::ControlModifier` check.
=> Refactored key handler in mediaview.cpp.

Telegram/SourceFiles/history/history.cpp
After my last patch (https://github.com/telegramdesktop/tdesktop/pull/5377) editing message on KeyUp now ignores messages with MediaWebPage.
So, the easiest way to fix this is to add a condition in the same place.
Of course we can add `bool MediaWebPage::allowsEditCaption()` and make it to return `true`, but this leads to the addition of unwanted code to `HistoryWidget::editMessage()`.
Sorry I didn't handle it right away. ¯\\\_(ツ)_/¯
=> Fixed skipping message with MediaWebPage on KeyUp.

Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp
UnityCounters is supported by KDE5 IconOnlyManager and Latte-dock, but using `env XDG_CURRENT_DESKTOP=Unity` causes some problems. This minimalistic change allows comfortable use Telegram in KDE5
=> Allow UnityCounters for KDE5 resolves #4554

Telegram/SourceFiles/apiwrap.cpp
Since appeared the albums in Telegram, for some reasons desktop client sends caption before album.
This pull request adds caption to first item of album to see caption under whole album.
What I do:
What I get now:
What I get after my patch:
=> Add caption to first item of album istead of sending separated message.

Telegram/SourceFiles/history/history_item.cpp, Telegram/SourceFiles/history/history_message.cpp, Telegram/SourceFiles/history/history_message.h, Telegram/SourceFiles/mtproto/type_utils.h
This PR fixes an issue, when a user can edit own unsupported messages (sent from an other client).
Of course after a resending of the edited message user receives `You cannot edit this message` alert. 
I think this is not right that the user has the ability to go into edit mode.
In the code.
I think it makes no sense to create a new subclass of unsupported message, just add one bool variable.
As I could see in other classes, it's normal to create a setter, that will be called from only one place. 
For example:
https://github.com/telegramdesktop/tdesktop/blob/e5536880fb9de5a46cc261e1f38c36230ec9f1c4/Telegram/SourceFiles/boxes/peer_list_box.h#L140-L145
I'm not sure that `!_isUnsupportedMessage` condition should be placed in `isTooOldForEdit()` method, so, unfortunately, I had to complicate …
=> Fixed an editing of own unsupported messages.

Telegram/Resources/langs/lang.strings, Telegram/SourceFiles/boxes/single_choice_box.cpp, Telegram/SourceFiles/boxes/single_choice_box.h, Telegram/SourceFiles/calls/calls_call.cpp, Telegram/SourceFiles/calls/calls_call.h, Telegram/SourceFiles/calls/calls_instance.cpp, Telegram/SourceFiles/calls/calls_instance.h, Telegram/SourceFiles/facades.cpp, Telegram/SourceFiles/facades.h, Telegram/SourceFiles/info/info_top_bar.cpp, Telegram/SourceFiles/platform/linux/specific_linux.cpp, Telegram/SourceFiles/platform/mac/specific_mac.mm, Telegram/SourceFiles/platform/platform_specific.h, Telegram/SourceFiles/platform/win/specific_win.cpp, Telegram/SourceFiles/settings/settings.style, Telegram/SourceFiles/settings/settings_calls.cpp, Telegram/SourceFiles/settings/settings_calls.h, Telegram/SourceFiles/settings/settings_common.cpp, Telegram/SourceFiles/settings/settings_common.h, Telegram/SourceFiles/settings/settings_main.cpp, Telegram/SourceFiles/storage/localstorage.cpp, Telegram/SourceFiles/storage/localstorage.h, Telegram/SourceFiles/ui/widgets/level_meter.cpp, Telegram/SourceFiles/ui/widgets/level_meter.h, Telegram/SourceFiles/ui/widgets/widgets.style, Telegram/gyp/telegram_sources.txt
This PR adds a new section to settings, allowing users to choose audio devices for calls, adjust volume, and disable audio ducking (on OS X).
Also, happy new year to everyone  🎅🏻🌲🎉
=> Add call settings

Telegram/SourceFiles/boxes/calendar_box.cpp, Telegram/SourceFiles/boxes/calendar_box.h
This PR adds `Left/Right arrow` shortcuts in CalendarBox to skip months.
In the code I've moved lambdas to private methods to avoid repeating same parts of the code.
=> Added shortcuts to skip months in CalendarBox.

Telegram/SourceFiles/core/application.cpp, Telegram/SourceFiles/mainwidget.cpp, Telegram/SourceFiles/mainwidget.h
[This issue](https://github.com/telegramdesktop/tdesktop/issues/5528) occurs because the application does not send the offline status when it quits.
Use case 1:
- User wants to quit the application.
- User opens a tray context menu by right click. — In this moment the main window loses focus and the application makes the status offline.
- User clicks "Quit Telegram". 
- Everything is okay.
Use case 2:
- User wants to quit the application.
- User presses `Ctrl + Q`.
- The application closes without changes of the online status.
- User is still online for awhile.
After this patch, user after pressing `Ctrl + Q` will have the offline status immediately.
=> Fixed a keeping online status after application quit.

Telegram/SourceFiles/mediaview.cpp
Trying again to fix fullscreen of mediaview on X11, related to #5607 , #5075 and #5048.
Tested it fixed mediaview in Arch Linux under:
* KDE Plasma (kwin 5.14.90)
* i3wm (4.16)
But strangely AwesomeWM 4.2 still misplaced the fullscreen window. But previous version of awesome (3.4 tested) was able to show the fullscreen window correctly so I suspect there are some bugs with  awesomewm 4.2 's end.
=> fixing mediaview fullscreen on X11

Telegram/SourceFiles/apiwrap.cpp, Telegram/SourceFiles/mainwidget.cpp, Telegram/SourceFiles/mainwidget.h, Telegram/SourceFiles/window/window_peer_menu.cpp
This PR fixes [this one](https://github.com/telegramdesktop/tdesktop/issues/5550).
But I'm not completely sure about the way of my solution.
Particularly not sure about using of the `MainWidget` singleton method to pass the `replyToId` value, but it is easier than passing the value through 2 child classes.
Reading of the local draft is needed when a user is in `Channel/Group info` and wants to create the poll from there. 
Generally it works and repeats patterns of the Android client's behavior.
=> Fixed sending polls as reply to other messages.

Telegram/Resources/langs/lang.strings, Telegram/SourceFiles/chat_helpers/message_field.cpp
This PR slightly improves the display of the "Create link" box title.
When url in box already exists title changes to "Edit link".
Seems like the `lng_formatting_link_edit_title` key was created for this, but it was forgotten to insert in the code.
=> Improved "Create link" box title display.

Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
This PR fixes a non-working Ctrl + F shortcut in the media view, which is covered by a `Command::Search` shortcut.
=> Fixed Ctrl + F shortcut for full screen toggle in media view.

Telegram/SourceFiles/app.cpp
Sorry for PR spamming. =) This one is pretty small.
As I said [here](https://github.com/telegramdesktop/tdesktop/pull/5618#issuecomment-458731027) before, after the fix of the online status while user quits, calling of `saveDraftToCloud()` became useless.
If user quits with offline status, his draft is already synced with the cloud.
If user quits with online status, his draft will be synced from `MainWidget::isQuitPrevent()`.
=> Removed unnecessary calling of saveDraftToCloud() method when quit.

Telegram/SourceFiles/info/info_section_widget.cpp
1. Resize the window to minimum width.
2. Open `View profile`/`View channel info`/`Settings`.
3. Maximize the window.
4. Return size of the window.
5. Crash.
The crash is due to the connection icon that was optimized here 26f1ade5ba22b2b351b12e3ce8cc179f2e013758.
=> Fixed crash in window resizing when layer is opened.

.travis/build.sh, docs/building-cmake.md, snap/snapcraft.yaml
Unfortunately, a few days ago the `libvdpau` repository switched to the Meson Build System and removed the `autogen.sh` shell file.
But before doing that, devs kindly created the `libvdpau-1.2` tag.
TDesktop doesn't use the Meson system anywhere, so we'll probably have to stay on that version for now.
<details><summary>Git Log</summary><blockquote>
</blockquote></details>
=> Updated libvdpau to 1.2.

Telegram/SourceFiles/apiwrap.cpp
This PR fixes a pretty rare improper display of the post author.
If user has no the last name, his forwarded messages locally will be display with extra space in the author section.
So I unified the creation of the `messagePostAuthor` string in the `ApiWrap` class.
=> Fixed extra space in a name of the post author after forwarding message.

Telegram/SourceFiles/dialogs/dialogs_widget.cpp, Telegram/SourceFiles/dialogs/dialogs_widget.h
It's a bit sad that there is scroll animation in the dialogs, but not in the dialog list. =(
So I added an animation to the scroll when it goes to top (e.g. the user pins the dialog).
The animation of the scroll to top repeats patterns of the scroll animation's behavior in the dialogs.
=> Added scroll animation in dialogs list when it scrolls to top.

Telegram/Resources/langs/lang.strings, Telegram/SourceFiles/history/history_inner_widget.cpp, Telegram/SourceFiles/history/history_item_components.cpp, Telegram/SourceFiles/history/history_item_components.h
When the author name of the channel post is too long, it is possible to see the author from the message header only when you forward this post to another chat.
So PR adds the author of the channel post in the tooltip when it is cut off.
Also this PR closes [this one](https://github.com/telegramdesktop/tdesktop/issues/5510).
=> Added author of channel post in tooltip.

Telegram/SourceFiles/history/history_inner_widget.cpp, Telegram/SourceFiles/history/media/history_media.h, Telegram/SourceFiles/history/media/history_media_sticker.h
Unfortunately, it is almost impossible to get the information from whom the sticker was forwarded.
The only way to see that is to start forwarding this forwarded sticker to someone, then it will be seen who the original author.
So this PR added a little more information in the tooltip of forwarded stickers.
=> Added forwarded info in tooltip of sticker.

Telegram/SourceFiles/apiwrap.cpp, Telegram/SourceFiles/ui/text/text.h
This PR is related to [this issue](https://github.com/telegramdesktop/tdesktop/issues/3145).
In another sending methods the zero width space is handled fine.
Perhaps the message box is unnecessary.
=> Added handler for "MESSAGE_EMPTY" error to delete a local message.

docs/building-xcode.md
I noticed that cmake could be install via brew and ninja was missing from the list
=> Add brew install cmake ninja

Telegram/SourceFiles/history/admin_log/history_admin_log_section.cpp, Telegram/SourceFiles/history/feed/history_feed_section.cpp, Telegram/SourceFiles/history/history_widget.cpp, Telegram/SourceFiles/info/info_top_bar.cpp, Telegram/SourceFiles/info/info_top_bar.h, Telegram/SourceFiles/info/info_wrap_widget.cpp, Telegram/SourceFiles/info/info_wrap_widget.h
This PR closes #5756.
In the code.
I moved a lambda of the search button into a separated method to avoid repeating parts of the code and to make it possible to call this method from the parent class.
Also I added shortcut as `Command::Search` instead of `Ctrl + F` to reach more flexibility.
=> Added Search Shortcut in Shared Media.

Telegram/SourceFiles/data/data_media_types.cpp, Telegram/SourceFiles/history/history_item.cpp, Telegram/SourceFiles/window/notifications_manager.cpp, Telegram/SourceFiles/window/notifications_manager.h
It is pretty annoying when someone sends you an album and you get several notifications of the same message.
So this PR combines the album messages in the single notification.
In the code.
I have noticed that the album grouping algorithm is very similar to the forwarded messages grouping algorithm. So I crossed them. A process is almost the same. In addition to checking the author of forwarded messages, I added checking the `groupId()`.
Also.
The `forwardedItem` was renamed to `forwardedOrGroupedItem`.
Removed unused `lng_in_dlg_album` keys in `MediaPhoto`, seems like it will never be used.
https://github.com/telegramdesktop/tdesktop/blob/e70465c633e03bbda2847f6cc42f892e1674c17a/Telegram/SourceFiles/data/data_media_types.cpp#L300-L312
Removed unused `ms` in `System::showNext()`. …
=>  Added grouping of album files into a single notification.

Telegram/SourceFiles/core/shortcuts.cpp, Telegram/SourceFiles/core/shortcuts.h, Telegram/SourceFiles/dialogs/dialogs_inner_widget.cpp
It is a little bit sad that we have `Ctrl+1-5` shortcuts for pinned dialogs, but still have no shortcut for the Saved Messages.
We just have to have it. =)
And of course it should be editable.
=> Added Shortcut to jump to the Saved Messages.

Telegram/SourceFiles/boxes/edit_caption_box.cpp, Telegram/SourceFiles/boxes/edit_caption_box.h
Unfortunately, tdesktop does not respect sizes of a custom video thumbnails. =(
This PR fixes it only for the EditCaptionBox.
In the code.
This is pretty easy when the media is a video or a not loaded GIF — we just take the dimensions from the thumbnail. 
But it comes harder when we have the loaded GIF. In that case we should separately save the dimensions of thumbnail and GIF. Then we can draw the thumbnail at the first second and then to draw the laoded GIF.
Before patch: [i.imgur.com/xDNsVg1.mp4](https://i.imgur.com/xDNsVg1.mp4)
After patch: [i.imgur.com/ioUvR02.mp4](https://i.imgur.com/ioUvR02.mp4)
=>  Fixed drawing of custom thumbnails in edit_caption_box.

Telegram/SourceFiles/data/data_peer.cpp, Telegram/SourceFiles/data/data_peer.h, Telegram/SourceFiles/window/window_peer_menu.cpp
There's nothing to export, so we don't need this option when chat is empty.
=> Removed "Export history" from context menu for empty chats.

Telegram/SourceFiles/boxes/edit_caption_box.cpp, Telegram/SourceFiles/storage/localimageloader.cpp, Telegram/SourceFiles/storage/localimageloader.h
In the code.
`editButton` should be calculated only if editing of media is allowed.
https://github.com/telegramdesktop/tdesktop/blob/14de1fe4858107bf8719191893e144681e09418f/Telegram/SourceFiles/boxes/edit_caption_box.cpp#L727-L731
=> Fixed checking of media editing in FileLoadTask.

Telegram/SourceFiles/history/history_widget.cpp
Sending files via drag and drop and via the attachment button does not work the same way.
If the user drag'n'drops file, the SendFilesBox appears, it works for any type of file, whether it's a photo, a video or document.
If the user opens file via attachment button (or `Ctrl + O`), the SendFilesBox appears only if file is a photo. If file is a document or video, it's uploaded immediately without any boxes.
In the code. 
Method `chooseAttach()` has unnecessary condition that cuts off all non-photo files.
https://github.com/telegramdesktop/tdesktop/blob/0f67f75bed0cc12f354450ffd032e8bdeaa4f15a/Telegram/SourceFiles/history/history_widget.cpp#L3066-L3073
Drag'n'drop method has no this condition and just calls `confirmSendingFiles()`. …
=> Fixed display SendFilesBox via historyAttach button.

Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
Parameter --no-desktop is deprecated and should not be used.
=> Fixed "Show in Folder" feature on Gnome 3.30+

Telegram/SourceFiles/core/launcher.cpp
the binary name deviates from the default .desktop name, setting it manually fixes the not displayed icon on Wayland mentioned in #5180
https://github.com/qt/qtwayland/blob/5.12/src/client/qwaylandwindow.cpp#L149
=> Linux: manually set desktop file name

Telegram/SourceFiles/core/launcher.cpp
Use optional compiler directive -DTDESKTOP_LAUNCHER_FILENAME to forward
required XDG desktop file name.
If not specified, fallback to default value will be used.
=> Allow GNU/Linux maintainers to forward launcher name

lib/xdg/telegramdesktop.appdata.xml
Fixed AppData validation error: tags cannot be empty.
Before:
```
$ appstream-util validate-relax --nonet telegramdesktop.appdata.xml
telegramdesktop.appdata.xml: FAILED:
• tag-invalid           : Expected children for tag
Validation of files failed
```
After:
```
$ appstream-util validate-relax --nonet telegramdesktop.appdata.xml
telegramdesktop.appdata.xml: OK
```
=> Fixed AppData validation error

Telegram/Patches/qtbase_5_6_2.diff
This limits the fix introduced in a058e75a to just 10.14.4, as #5858 seems to be fixed in 10.14.5.
=> Re-enable integrated GPU on macOS.

Telegram/SourceFiles/history/history_widget.cpp
The commit in https://github.com/telegramdesktop/tdesktop/pull/5478 doesn't behave the same as dragging:
When selecting any file to send via the `historyAttach` button, the compressed parameter of `HistoryWidget::confirmSendingFiles` is always set to `CompressConfirm::Auto`:
https://github.com/telegramdesktop/tdesktop/blob/48cee21b9f5f372dab64e9baf829b425e71e3c45/Telegram/SourceFiles/history/history_widget.cpp#L3088
This causes the `SendFilesBox` to infer the type of the file as whatever it was set to last:
https://github.com/telegramdesktop/tdesktop/blob/48cee21b9f5f372dab64e9baf829b425e71e3c45/Telegram/SourceFiles/boxes/send_files_box.cpp#L1456-L1468
Which means if photo was selected last, then the sticker is sent as a photo (though it still initially displays as a sticker on the client …
=> Fix stickers sending as photos in certain situations

Telegram/SourceFiles/layout.cpp
Minor improvements: 
I realized that Office 2013+ extensions(.pptx, .xlsx, .docx) didn't have layout colors.
=> Enable to handle .pptx .xlsx .docx extensions

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
This lets unread message count work if the app is build with custom `TDESKTOP_LAUNCHER_FILENAME` define.
=> Make .desktop file search respect TDESKTOP_LAUNCHER_FILENAME

Telegram/SourceFiles/boxes/peers/add_participants_box.cpp, Telegram/SourceFiles/boxes/peers/add_participants_box.h, Telegram/SourceFiles/dialogs/dialogs_search_from_controllers.cpp, Telegram/SourceFiles/dialogs/dialogs_search_from_controllers.h, Telegram/SourceFiles/dialogs/dialogs_widget.cpp
This is PR #5728 but with a fix that allows searching for your own messages. Also [this request](https://github.com/telegramdesktop/tdesktop/pull/5728#pullrequestreview-212555077) has been done.
The original PR message from @TheWug follows:
-----
fixes #5667
Change `Dialog::SearchFromController` to inherit not from `ParticipantsBoxController`, which only shows the users in the group, but instead from `AddSpecialBoxController` which shows the group's users but falls back on global search as well.
I know you don't generally accept pull requests for features and calling this a bug is very borderline but I figured I'd post it anyway.
=> Allow searching for messages by a user who has left a chat, fixes #5667

Telegram/SourceFiles/history/view/media/history_view_web_page.cpp, Telegram/SourceFiles/history/view/media/history_view_web_page.h
This PR closes #6421.
You can now click link preview title to open the link that generated it. If site title does not exist, page title will be used for link instead.
Also you can select and copy site link along with page title and description.
=> Make link preview title clickable

Telegram/Resources/langs/lang.strings, Telegram/SourceFiles/boxes/calendar_box.cpp, Telegram/SourceFiles/boxes/calendar_box.h, Telegram/SourceFiles/window/window_session_controller.cpp
This pull request adds functionality to jump to first message by pressing "Beginning" button when selecting date.
Additionaly, you can press **Home** button on keyboard while calendar is open.
=> Added "Beginning" button to calendar

Telegram/SourceFiles/window/themes/window_theme_preview.cpp
If you set `msgInBg` color to semi-transparent, you'll see that tail of last message in theme preview will overlay message bubble. The problem is: if `QPainter->setClipping(false)` was called, then first clip instruction (in this case `setClipRegion` for cutting bubble corner) will be skipped.
Current state (1.8.7 beta):
After fix (this pull):
=> Fix last message tail drawing in theme preview

Telegram/SourceFiles/history/admin_log/history_admin_log_filter.cpp
Here's a demonstration of the behaviour that this fixes: https://giant.gfycat.com/ImpressionableDefiniteFieldspaniel.webm
=> Fix "All users and admins" checkbox in admin log filter box not unchecking all admins

.travis/build.sh
libxkbcommon won't build on Travis if there is no cache because of missing tag checkout.
=> Use exact version of libxkbcommon in Travis build

Telegram/SourceFiles/history/history_widget.cpp
Since supergroup admins can edit their messages without limit, timer is not needed there.
=> Do not show edit timer for supergroup admins

.appveyor/install.bat, .travis/build.sh, Telegram/SourceFiles/boxes/single_choice_box.cpp, Telegram/SourceFiles/chat_helpers/emoji_keywords.cpp, Telegram/SourceFiles/chat_helpers/emoji_sets_manager.cpp, Telegram/SourceFiles/data/data_channel.cpp, Telegram/SourceFiles/dialogs/dialogs_inner_widget.cpp, Telegram/SourceFiles/export/data/export_data_types.cpp, Telegram/SourceFiles/history/history_inner_widget.cpp, Telegram/SourceFiles/history/view/media/history_view_poll.cpp, Telegram/SourceFiles/media/streaming/media_streaming_reader.cpp, Telegram/SourceFiles/ui/grouped_layout.cpp, Telegram/SourceFiles/ui/image/image_prepare.cpp, Telegram/SourceFiles/ui/text/text_entity.cpp, Telegram/gyp/common/win.gypi, docs/building-cmake.md, docs/building-msvc.md, docs/building-xcode.md, snap/snapcraft.yaml
This made 5 changes to the current code base to be compatible with higher versions of range-v3 library.
1. ranges::iterator_range was renamed to subrange, see https://github.com/ericniebler/range-v3/issues/766
2. PercentCounterItem need an operator== for ranges::sort for some reason
3. include <range/v3/to_container.hpp> changed to include <range/v3/range/conversion.hpp>
4. explicitly specify the upper bound in ranges::view::ints
5. change the deprecated ranges::to_ (with underscore) to ranges::to (without underscore)
=> be compatible with range-v3 0.9.x/1.0 branch

Telegram/SourceFiles/history/history.style, Telegram/SourceFiles/history/view/media/history_view_photo.cpp
This PR solves two problems by resizing message with photo when it's bubbled (i.e. have additional text like caption or author name).
It takes too many lines and it's hard to read this.
=> Resize message with photo when bubbled

Telegram/Resources/langs/lang.strings, Telegram/SourceFiles/data/data_peer.cpp, Telegram/SourceFiles/history/history_widget.cpp, Telegram/SourceFiles/history/view/history_view_scheduled_section.cpp
With this PR users can see their restriction date in blocked message field/inline bot suggestions/sticker box/GIF box.
Currently text tells only "You have been restricted" without date.
=> Show restricted date to user

Telegram/SourceFiles/inline_bots/inline_results_widget.cpp
=> Fixed inline message restriction width

docs/building-cmake.md, docs/building-msvc.md
1. Corrected commit to checkout for `ThirdParty/patches`: `b0ec5df4` was not found. Probably `b0ec5df` was implied as it was used on `Libraries/patches`.
2. Removed `git checkout tdesktop` for zlib since `desktop-app/zlib` doesn't have `tdesktop` branch.
1. Since googletest is empty, it should be cloned manually (with removal of empty folders beforehand).
2. CMake can't find `minidump_upload.m` because it doesn't exist. Actual file that needs to be searched is `minidump_upload.cc`. There is only one match and no false positives, so it should be safe to replace it with sed.
=> Fixes for build instructions

Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp
When building TD 1.9+ from sources, animated stickers are breaking after first play cycle. This patch corrects typo in ffmpeg_utility, which fixes this problem.
=> Fixed animated stickers cache

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
Capabilities "actions" and "body-markup" can be available at the
same time.
=> libnotify: capabilities are not exclusive

Telegram/SourceFiles/window/window.style
It would be awesome to have Telegram Desktop on the [librem5](https://puri.sm/products/librem-5/). Since the app is already adaptive there isn't much to change, but the min width of 380px is slightly to wide. Therefore this changes the width to 360 which doesn't impact the functionality of Telegram Desktop, but allows it to run on the phone without shooting out of the screen.
=> Replace min width of 380px width 360px

Telegram/cmake/lib_tgvoip.cmake
This avoids matching against other 32bit arches like armv7/armhf that
doesn't have msse2 but are 32bit and need other 32bit-specific flags to
allow for compilation like -g0.
=> [] lib_tgvoip.cmake: Match against x86 arches.

Telegram/cmake/telegram_options.cmake
Fixed TDESKTOP_LAUNCHER_FILENAME option. Missed after switching from GYP to CMake.
=> Fixed TDESKTOP_LAUNCHER_FILENAME option

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
This makes the code a bit simpler and compatible with Qt 5.9 since the QString::chopped method is not used.
=> Use QStringList::join to print notifications capabilities

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp, Telegram/SourceFiles/platform/linux/notifications_manager_linux.h
On supported notification servers (currently only KDE Plasma 5.18+) this
action will create a reply text field inside the notification.
=> Implement inline-reply

Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp, Telegram/SourceFiles/platform/linux/linux_desktop_environment.h, Telegram/SourceFiles/platform/linux/specific_linux.cpp
This PR
* adds flatpak to PreferAppIndicatorTrayIcon since Qt has problems with SNI implementation in flatpak
* removes Awesome since Qt icon works well with it and Awesome users use startx in general, that doesn't set XDG_CURRENT_DESKTOP/DESKTOP_SESSION anyway
* removes XFCE since Qt icon works well with it
* removes MATE since it is not GNOME and works well with Qt icon also
* adds the check for a path in DESKTOP_SESSION
* adds pavucontrol-qt to OpenSystemSettings
=> Desktop environment detection fixes

Telegram/CMakeLists.txt
Telegram [uses][1] long atomic types, so at least on 32-bit ARM, MIPS, and PowerPC linking against libatomic is needed.
[1]: https://github.com/telegramdesktop/tdesktop/blob/2c64676415a8ddc8340f9337bff8691aed47cdf2/Telegram/SourceFiles/export/output/export_output_stats.h#L28
=> Perform test for additional libatomic

Telegram/SourceFiles/facades.cpp
This PR fixes "hashtag bug".
How to reproduce:
1. Open archived chats
2. Click on any hashtag in chat or channel
What should happen:
What actually happens:
Additionally, if you click "X" button near channel or chat name, you'll get this:
=> Fix opening hashtag when in archive

Telegram/SourceFiles/data/data_peer.cpp
This PR fixes "private linked channel bug".
How to reproduce:
1. Find or make a group that linked to private channel as a discussion.
2. Find a message from this channel in chat (post it if there are no messages).
3. Click channel profile pic or channel name in message.
Expected:
You open linked channel of this discussion group.
Actual behavior:
You'll receive "Sorry, this channel is not accessible." message, though it works fine when opening from arrow button that leads to post.
=> Fix opening private linked channel from message

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
Can help with #3216, but for larger icons App::wnd()->iconWithCounter should be reworked :(
Fixes #1908
=> Use system icon theme and increase icon size

.github/workflows/linux.yml, docs/building-cmake.md
This enables the use of [Qt's own event dispatcher](https://github.com/qt/qtbase/blob/dev/src/corelib/kernel/qeventdispatcher_unix.cpp) instead of [glib one](https://github.com/qt/qtbase/blob/dev/src/corelib/kernel/qeventdispatcher_glib.cpp)
See also: https://github.com/desktop-app/cmake_helpers/pull/20
=> Remove glib dependency from Qt

Telegram/SourceFiles/boxes/add_contact_box.cpp, Telegram/SourceFiles/boxes/create_poll_box.cpp, Telegram/SourceFiles/boxes/edit_caption_box.cpp, Telegram/SourceFiles/boxes/peers/edit_peer_info_box.cpp, Telegram/SourceFiles/boxes/rate_call_box.cpp, Telegram/SourceFiles/boxes/report_box.cpp, Telegram/SourceFiles/boxes/send_files_box.cpp, Telegram/SourceFiles/boxes/share_box.cpp, Telegram/SourceFiles/history/view/history_view_compose_controls.cpp, Telegram/SourceFiles/support/support_helper.cpp, Telegram/SourceFiles/window/notifications_manager_default.cpp
Respect user settings "Send by ..." for:
- forward dialog
- send file dialog
- edit caption dialog
- schedule messages
- new channel dialog
- group description edit dialog 
- rate call dialog
- report bot dialog
- support mode
Fixes #6634.
Change Enter only to Enter and Ctrl+Enter in create poll dialog.
=> Respect user settings "Send by ..."

.github/workflows/linux.yml, docs/building-cmake.md
Anongit of FreeDesktop is not working now, and because of that libvdpau won't clone.
Since FreeDesktop uses GitLab instance for their projects, this PR changes libvdpau source url to their GitLab.
=> Changed libvdpau source url

.github/workflows/linux.yml, snap/snapcraft.yaml
* Remove intermediate build directories in Linux workflow.
* Use fixed version v3.16.3 of CMake in Snap workflow.
=> Fix builds for linux

Telegram/SourceFiles/platform/linux/specific_linux.cpp, Telegram/cmake/telegram_options.cmake
This removes TDESKTOP_DISABLE_DESKTOP_FILE_GENERATION macro that has no sence since schema registration won't work without desktop file generation.
Inested, added an environment variable with the same name which closes #306
=> Convert TDESKTOP_DISABLE_DESKTOP_FILE_GENERATION to runtime environment variable

Telegram/cmake/telegram_options.cmake
GTK integration is used only for GTK file dialog, so there are no need in separate option in cmake
Enabling of TDESKTOP_FORCE_GTK_FILE_DIALOG is changed to by `NOT DESKTOP_APP_USE_PACKAGED` rather than by `NOT DESKTOP_APP_SPECIAL_TARGET STREQUAL ""` since any static build has ugly file dialog (also debug builds on GitHub actions would have GTK file dialog due to this change)
=> Remove separate switch for GTK integration and fix condition for GTK file dialog

Telegram/SourceFiles/data/data_document.cpp
When displaying large numbers of GIFs, Telegram's Media Cache runs out of size and unloads items that are still being displayed.
You can see this issue in this video:
https://twitter.com/avwuff/status/1220169234682195970
**BACKGROUND:**
Telegram Desktop has an internal media cache limit, hardcoded to 32 megabytes.  When more than 32 mb of media is in memory, the media cache starts to unload items.  However, sometimes the items being unloaded are still on screen, resulting in them immediately trying to load themselves back into memory.
This can be seen with the flickering stickers.  What you are seeing is the following:
1. Normal sticker is being drawn
2. Normal sticker is unloaded, causing the blurry thumbnail to be drawn
3. This will also trigger the sticker to be loaded again
4. Now the …
=> Increase media cache memory size to solve flicker issue

Telegram/SourceFiles/core/launcher.cpp
For automatic usage in window titles, tray tooltips and etc.
=> Set application display name

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
Otherwise there are a dummy icon when tray counter is disabled
=> Disable SNI tray icon name setting in snap

.github/workflows/linux.yml, docs/building-cmake.md
* Disable building of unneeded openal tools and tests
* Disable ffmpeg linkage with unneeded libraries
* Disable unneeded dtd validation for libwayland
* Omit Qt flags that set to default values
* Fix prefix usage
* Build dependencies in release mode to reduce build size
=> Fixes for linux action:

Telegram/SourceFiles/storage/localimageloader.cpp
Telegram can already play .ogg Vorbis and Opus files correctly on Desktop and Android.
But .opus and .oga files sent from the Desktop app won't get marked as audio files.
This pull request will make any .opus and .oga files actually marked as music files that can be read from Telegram directly.
I've tested it and files sent from the patched client will work correctly on the current Desktop app and Android app.
Related issues: #5840 #1754
=> Add .opus and .oga files as song formats

Telegram/SourceFiles/core/crash_report_window.cpp
Since setFamily in QApplication::setFont was removed
=> Restore setFamily in crash report window

Telegram/SourceFiles/boxes/peer_list_box.h, Telegram/SourceFiles/boxes/peers/edit_participants_box.cpp, Telegram/SourceFiles/calls/calls_box_controller.cpp, Telegram/SourceFiles/info/profile/info_profile_members_controllers.cpp, Telegram/SourceFiles/info/profile/info_profile_members_controllers.h
With this PR bot privacy status will be shown in group member list instead of "bot". Fixes #5344.
Before PR:
After PR:
This also includes group members manage box:
=> Show bot privacy status in members list

Telegram/Resources/langs/lang.strings, Telegram/SourceFiles/boxes/peers/edit_participants_box.cpp, Telegram/SourceFiles/boxes/peers/edit_peer_info_box.cpp, Telegram/SourceFiles/history/view/history_view_top_bar_widget.cpp, Telegram/SourceFiles/info/info_top_bar.cpp, Telegram/SourceFiles/info/profile/info_profile_actions.cpp, Telegram/SourceFiles/info/profile/info_profile_cover.cpp
This PR changes "members" to "subscribers" in channels, since other official apps uses it too. Fixes #6181.
=> Use "subscribers" instead of "members" in channels

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
For some reason this is needed for newer Qt in flatpak
=> Fix decoration applying and trigger repainting on update

Telegram/SourceFiles/info/media/info_media_inner_widget.cpp, Telegram/SourceFiles/info/profile/info_profile_inner_widget.cpp
This PR moves "X groups in common" button in profile after media types, since "common groups" is not a media type itself. Fixes #5476.
Before:
After:
=> Move "X groups in common" in shared media to bottom

.github/workflows/linux.yml, docs/building-cmake.md
Since it loaded at runtime with dlopen anyway and headers from the system package are OK
=> Remove Portaudio from building instructions

Telegram/SourceFiles/media/audio/media_audio_capture.cpp
This makes https://github.com/telegramdesktop/tdesktop/issues/1548 don't affect on startup, but only when capture feature is used
=> Check only if at least one audio device is exist on startup

.github/workflows/mac.yml
macOS action has runner version in the workdir path, it should be a part of the cache key
=> Fix macOS cache validating

docs/building-msvc.md
1. in vs2019 building instructions, the script doesn't quit to the BuildPath folder
2. the QT Visual Studio tool is located in menu **Extensions** -> **Manage Extensions** in vs2019
=> Fix the VS2019 Building instructions

Telegram/SourceFiles/core/sandbox.cpp
Looks like `QApplication::setFallbackSessionManagementEnabled(false)` is not enough
=> Disable restart on session start explicitly

Telegram/SourceFiles/media/view/media_view_pip.cpp
Since startSystemMove is the only way to move a window on Wayland
And since custom resize works bad due to the lack of moving (resize with left and top corners works just like resize with right and bottom corners)
=> Use startSystemMove/startSystemResize in PiP window on Wayland

docs/building-msvc.md
Build docs for Windows are at older commit of desktop-app/patches, which causes build failure with patched Qt. This PR fixes it.
=> Fix patches revision

Telegram/SourceFiles/data/data_document.cpp
See commit message for more details.
I might in the future create another pull request to actually use the PDF thumbnail generation ability to show a PDF thumbnail, but from a quick glance at the code I only saw codepaths for server side thumbnail previews, not any for generating one from local files only.
So it wasn't worth the hassle for a feature that will be used by 1% of users, because 99% will have a tdesktop without QtWebengine, thus no PDF thumbnail feature.
I might be wrong though and if you think it won't be much extra work to add that feature, then please give me a hint and I will work on it.
=> Fix pdf being opened as image

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
To avoid situations when StatusNotifierItem registers icon, but tdesktop assumes that there are still no SNI
=> Don't request IsStatusNotifierHostRegistered when SNI become available

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
Fixes a regression with new Cinnamon on Mint 20 (left one is the release version, right one is this PR)
=> Don't generate 64px tray icon since badge counter generator doesn't support it

Telegram/SourceFiles/export/output/export_output_abstract.cpp
Instead of ChatExport_06_07_2020 we get ChatExport_2020-07-06, which conforms to ISO 8601 and has the advantage that it cannot be misinterpreted in countries where it is common to start with the month instead of the day.
Also sorting directories by name now also means automatically being chronologically sorted.
See #6020
=> Export chats with ISO 8601 dates

Telegram/CMakeLists.txt, Telegram/SourceFiles/platform/linux/specific_linux.cpp
CheckCXXSourceCompiles is not needed anymore
Material wayland decorations could be checked just with IsQtPluginsBundled
=> Little cleanup for Linux platform code & build

Telegram/SourceFiles/platform/linux/specific_linux.cpp
Before 6635d03818c90f62cfddb516acadc293255b8905 XCBLastUserInputTime could fail only when there are no X connection, after that it is clear that it can fail even with X connection and fallback is needed.
=> Fallback to D-Bus methods if XCB-based LastUserInputTime failed

Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
To avoid overlapping by panels in KDE
=> Add always on top hint for media view window

.github/workflows/linux.yml, docs/building-cmake.md
https://github.com/01org/libva doesn't exist anymore
=> 01org/libva -> intel/libva

Telegram/SourceFiles/platform/linux/specific_linux.cpp
Looks like 108 is the length including \0, therefore actual limit is 107
Fixes #8883
=> Change socket path length condition to >=

Telegram/SourceFiles/platform/linux/specific_linux.cpp
It is not guaranteed that app is running with the same Qt version that was compiled
=> Check Qt version in runtime in CanOpenDirectoryWithPortal

Telegram/SourceFiles/data/data_document.cpp
External player feature doesn't work otherwise
=> Don't stream videos when external player is used

Telegram/SourceFiles/media/clip/media_clip_ffmpeg.cpp
It should been removed in 7d29f9ce17c837a0ae2944f5b2c75dc16c9f61f6, but was forgotten
=> Remove forgotten sws_scale check

snap/snapcraft.yaml
snapd has been fixed the issue with portals dbus activation a long time ago, so this shouldn't generate too much reports as it was this summer
Portals offer a native dialog for the DE used by a user that can show all files on the host and pass-through them via the sandbox. Qt uses them by default in snap if there is no override.
=> Try to use portals for file dialog in snap, again

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
Since tdesktop gets icon theme pretty well now, there's no need for any workaround.
=> Remove the last workaround in tray implementation

README.md
As the licence was moved out of the source directory we need to change this link.
=> Fix WebRTC licence link

.github/workflows/linux.yml, Telegram/CMakeLists.txt, Telegram/SourceFiles/platform/linux/linux_wayland_integration.cpp, Telegram/SourceFiles/platform/linux/linux_wayland_integration.h, Telegram/SourceFiles/platform/linux/linux_wayland_integration_dummy.cpp, Telegram/SourceFiles/platform/linux/specific_linux.cpp, Telegram/SourceFiles/platform/linux/window_title_linux.cpp, Telegram/SourceFiles/platform/linux/window_title_linux.h, Telegram/SourceFiles/qt_static_plugins.cpp
Add `DESKTOP_APP_DISABLE_WAYLAND_INTEGRATION` to control the dependency on QtWayland.
Related feature request: https://github.com/telegramdesktop/tdesktop/issues/9031
Submodule pull request: https://github.com/desktop-app/cmake_helpers/pull/67
=> Build wayland support optionally

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
Looks like there are support for this size since b703f4e5557053d4cc320e42861db197c0ce7790
=> Restore 16px tray icon size

Telegram/SourceFiles/platform/linux/specific_linux.cpp
QGnomePlatform changed its detection method as well https://github.com/FedoraQt/QGnomePlatform/commit/23ee752d31069c222ab2e05ce4c37482fc22ddf4
=> Detect more dark themes on Linux

Telegram/SourceFiles/media/player/media_player_instance.cpp
Looks like Qt maps "Media Play" to the common play/pause button on keyboards:
https://github.com/qt/qtbase/blob/5.15/src/platformsupport/input/xkbcommon/qxkbcommon.cpp#L293
https://github.com/qt/qtbase/blob/5.15/src/plugins/platforms/windows/qwindowskeymapper.cpp#L392
https://github.com/qt/qtbase/blob/5.15/src/plugins/platforms/android/androidjniinput.cpp#L519
https://github.com/qt/qtbase/blob/5.15/src/plugins/platforms/android/androidjniinput.cpp#L607
While "Toggle Media Play/Pause" is some special case:
https://github.com/qt/qtbase/blob/5.15/src/plugins/platforms/windows/qwindowskeymapper.cpp#L488
https://github.com/qt/qtbase/blob/5.15/src/plugins/platforms/ios/quiview.mm#L584
It is worth to behave on "Media Play" like on "Toggle Media Play/Pause".
Fixes #3342
=> Media Play key is expected to behave like Toggle Media Play/Pause

docs/building-msvc-x64.md, docs/building-msvc.md
there is a submodule that need to clone, see https://github.com/desktop-app/tg_owt/tree/master/src/third_party
=> Update VS2019 build instructions

Telegram/CMakeLists.txt, Telegram/SourceFiles/platform/linux/linux_gsd_media_keys.cpp, Telegram/SourceFiles/platform/linux/linux_gsd_media_keys.h, Telegram/SourceFiles/platform/linux/main_window_linux.cpp, Telegram/SourceFiles/platform/linux/main_window_linux.h, Telegram/SourceFiles/platform/win/main_window_win.cpp
This fixes media keys handling on (but not limited to, probably):
* GNOME
* Cinnamon
* MATE
* Budgie
* Pantheon (elementaryOS)
* Unity
Fixes #3960
=> Add support for G-S-D's media-keys extension

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
Even though they're the same, there should be interface specified
=> Fix kSNIWatcherService/kSNIWatcherInterface misusage

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
These icons should have a dot indicating unread messages, counter is redudant for them
=> Don't add counter when icon theme has 'panel' icon

Telegram/SourceFiles/platform/linux/linux_gtk_integration.cpp
Have this order for scaling settings:
1. devicePixelRatio
2. GTK
3. DPI
=> Don't mess GTK scale factor with other scaling settings

snap/snapcraft.yaml
ARM support is community maintained in tg_owt and no one seem to fix build with NEON, thus disabling it to get new armhf builds on snapcraft.
=> Build WebRTC without NEON for armhf

Telegram/CMakeLists.txt, Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp, Telegram/SourceFiles/platform/linux/linux_gtk_file_dialog.cpp, Telegram/SourceFiles/platform/linux/linux_gtk_file_dialog.h, Telegram/SourceFiles/platform/linux/linux_xdp_file_dialog.cpp, Telegram/SourceFiles/platform/linux/linux_xdp_file_dialog.h, Telegram/SourceFiles/platform/linux/specific_linux.cpp
This allows to use portal dialogs more flexibly (e.g. fallback mechanism)
This also allows to have any changes we want for portal dialogs without patchig Qt
No more need to override QT_QPA_PLATFORM to use portal dialogs
=> Add XDG Desktop Portal based file dialog implementation from Qt

Telegram/SourceFiles/platform/linux/specific_linux.cpp
Since it's widely used (by AppImages, for instance)
=> Read DESKTOPINTEGRATION variable instead of TDESKTOP_DISABLE_DESKTOP_FILE_GENERATION

Telegram/build/docker/centos_env/Dockerfile
nproc is used everywhere except for building webrtc
=> set nproc for number of jobs to build webrtc in docker

Telegram/cmake/td_scheme.cmake
This fixes "relocation truncated to fit ..." error on final linking. It should not introduce a lot of overhead since the code is used only in network communications.
This errors appears sometimes and I do not know exact conditions, I daresay it is related to large size of an object file with the schema.
More docs see at https://gcc.gnu.org/onlinedocs/gcc/MIPS-Options.html#index-mxgot-1
Example of failed build: https://buildd.debian.org/status/fetch.php?pkg=telegram-desktop&arch=mips64el&ver=2.5.8%2Bds-1&stamp=1612773725&raw=0
=> Add -mxgot flag to td_scheme on MIPS64

Telegram/SourceFiles/chat_helpers/bot_keyboard.cpp
Add additional bot commands binds for moderators.
Clicking on them with mouse is tedious, but they still work just as regular commands.
I edited Key_9 to Key_2 because there is just 2 buttons in the bot and I suggest none will be added in the near future. Also binding existing commands to Key_3 and Key_4 helps to stay one-handed either on keyboard itself or on a numpad.
=> Expand moderating mode

Telegram/SourceFiles/info/profile/info_profile_actions.cpp
Since v2.6.0, clicking the "Report" button on the profile page does not pop up the ReportBox.
This PR fixed this bug.
=> Complete report action callback

Telegram/SourceFiles/dialogs/dialogs_inner_widget.cpp, Telegram/SourceFiles/platform/linux/specific_linux.cpp
https://github.com/KDE/clazy/blob/master/docs/checks/README-qstring-insensitive-allocation.md
=> Avoid allocations for case-insensetive compare

Telegram/SourceFiles/config.h, Telegram/SourceFiles/platform/linux/launcher_linux.cpp
Qt already [provides](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qglobal.h?h=v5.15.2#n101) a similar macro.
=> Rely on QT_STRINGIFY instead of custom macro

Telegram/SourceFiles/calls/calls_group_panel.cpp, Telegram/SourceFiles/calls/calls_panel.cpp, Telegram/SourceFiles/core/application.cpp, Telegram/SourceFiles/core/application.h, Telegram/SourceFiles/media/view/media_view_pip.cpp, Telegram/SourceFiles/settings/settings_notifications.cpp, Telegram/SourceFiles/ui/widgets/separate_panel.cpp, Telegram/SourceFiles/window/notifications_manager_default.cpp
It was introduced to workaround the absence of size hints propagating in Qt 5.12 Wayland backend, there's no need in it anymore
=> Get rid of modal parent hack

Telegram/SourceFiles/media/view/media_view_pip.cpp, Telegram/SourceFiles/media/view/media_view_pip.h
Depends on https://github.com/desktop-app/lib_ui/pull/48
=> Workaround force setting of WM_TRANSIENT_HINT in Qt's xcb backend

Telegram/SourceFiles/mtproto/session.cpp, Telegram/SourceFiles/mtproto/session.h
Commit bdc7f4114faa472407e5afbc27eb826e4cd38bf2 got rid of `_timeouter`'s callback without removing the timer that still fires every second.
=> Remove dangling timer in MTP Session

Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp, Telegram/SourceFiles/media/view/media_view_overlay_widget.h
Very useful, especially on large monitors.
Since the permanent opening of the video in full screen interferes and hide other applications.
This functionality allows remembering (in the current session) that the window has been switched to a PIP mode and will open a new video directly in the PIP mode.
=> Remember that media view was switched to PIP and open it as PIP again.

.gitignore
CLion IDE generates cmake-build-debug and .idea files, which is not ignored by tdesktop .gitignore.
=> Added CLion-generated files to .gitignore

Telegram/SourceFiles/mtproto/session_private.cpp, Telegram/SourceFiles/mtproto/session_private.h
The check of sent requests and containers is done unconditionally every second even though the request timeout is 10 seconds and the container timeout is 600 seconds. This commit uses fine grained timers instead in order to avoid useless system wake-up events.
The check of sent requests is now scheduled on demand when a new request is queued. Then the callback, while parsing queued requests, computes the delta to the closest expiring request and automatically schedules the next check if necessary.
Given the high value of the container timeout, its callback is called repeatedly every 600 seconds, unless it computes a lower delta for an expiring container using the same logic as for the requests.
=> Use fine grained session timers

Telegram/SourceFiles/history/view/controls/history_view_voice_record_button.cpp
Enabling animations triggers an animation of the voice record button that keeps firing uselessly at ~120 calls per second until the button is manually toggled. The animation callback cannot stop itself since it expects the button to be visible.
This commit fixes the issue by preventing spawning the animation if the widget is hidden.
=> Fix voice record button infinite animation

README.md
Since there are different methods to build for VS for 32 and 64 bits, I think it'd be good to split the label
=> Update README.md to split VS2019 32 and 64 bits

Telegram/SourceFiles/chat_helpers/bot_keyboard.cpp
Add missing /undo, /next, /stats options
Add 5 and 6 keys as translating option for NumPad
Also, revert previous key check for bot keyboard, as it now does not recognize 3-9 keys as inputtable numbers for some reason.
=> Expand moderating mode some more

Telegram/Resources/langs/lang.strings, Telegram/SourceFiles/boxes/sticker_set_box.cpp, Telegram/SourceFiles/boxes/sticker_set_box.h
This PR allow user archive sticker pack to Archive Stickers via Telegram Desktop.
Closes #2357
=> Add "Archive Sticker" into Sticker Box 3dots menu

Telegram/SourceFiles/media/view/media_view_pip.cpp, Telegram/SourceFiles/media/view/media_view_pip.h
Add volume toggle and volume level controls to the PiP window.
I used a combination of styles volume controls from PlaybackControls (toggle icons + volume level control length) and progress control from PiP window (volume level control width and style). It looks very natural. But perhaps it makes sense to add new constants.
The location of the controls can also be discussed, but in this view it fits into the current interface as organically as possible, when you go to the PiP window, the close and window mode buttons move to one corner, and the sound control buttons to another.
Linux/Windows controls position
MacOS controls position
=> Add volume controls to PiP window

README.md
The previous link led to the license text which was relevant up to [v26.0.2](https://github.com/rastikerdar/vazir-font/tree/v26.0.2), but removed in [v27.0.0](https://github.com/rastikerdar/vazir-font/blob/v27.0.0/LICENSE)
=> Actual link to Vazir Fonts license in README

Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp, Telegram/SourceFiles/media/view/media_view_overlay_widget.h
Bug:
Sometimes changing of the volume level or mute/unmute has no effect.
It happens because Fader::onTimer get a current volume level from the Mixer,
but it gets an event about the volume modification from the settings.
Bug appear when the method onTimer calling between updating
of the settings and the Mixer volume.
Solution:
Updating the Mixer volume before the settings.
(maybe will be better to get the volume level
from the settings in place of the Mixer,
but I am not sure about other side effects of this)
=> Fix video player volume level changing

Telegram/SourceFiles/platform/linux/linux_gdk_helper.cpp
This patch avoids linking issues that previously weren't present.
Regression introduced in https://github.com/telegramdesktop/tdesktop/commit/680a9a7ca7d9dde6c79a6340e3ca003e6ccfd8a5
```
In file included from /home/.root/var/tmp/portage/net-im/telegram-desktop-2.7.8/work/tdesktop-2.7.8-full/Telegram/SourceFiles/platform/linux/linux_gdk_helper.cpp:11:
/home/.root/var/tmp/portage/net-im/telegram-desktop-2.7.8/work/tdesktop-2.7.8-full/Telegram/SourceFiles/platform/linux/linux_gdk_helper.cpp: In function ‘void Platform::internal::{anonymous}::GdkHelperLoadGtk2(QLibrary&)’:
/home/.root/var/tmp/portage/net-im/telegram-desktop-2.7.8/work/tdesktop-2.7.8-full/Telegram/SourceFiles/platform/linux/linux_gdk_helper.cpp:84:30: error: ‘::gdk_x11_drawable_get_xdisplay’ has not been declared; did you mean …
```
=> Fix building with LINK_TO_GTK

Telegram/CMakeLists.txt, Telegram/SourceFiles/platform/linux/linux_wayland_integration.cpp, Telegram/SourceFiles/platform/linux/linux_wayland_integration.h, Telegram/SourceFiles/platform/linux/linux_wayland_integration_dummy.cpp, Telegram/SourceFiles/platform/linux/main_window_linux.cpp, Telegram/SourceFiles/platform/linux/main_window_linux.h
This reverts commit 79f96480c2e8265d591818173015690f7de4bc5a.
Fixes #16563
=> Revert "Use QMenuBar instead of own global menu implementation on Linux"

Telegram/SourceFiles/chat_helpers/bot_keyboard.cpp
Apparently for commands to work, they have to be bind to 1-9 keys, apart from any other alternative hotkeys. It should address this issue, as well as expanding to ease the usage on numpad.
=> Expand moderator mode + fix

Telegram/SourceFiles/calls/calls_panel.cpp
Having an empty window title brings different issues, for example:
* invisible on task bar
* invisible in task switcher
* apply properties by match
* ...
So let's use the contact user name for window title.
Fixes #10243
=> window title for call window

Telegram/build/setup.iss
Closes #16619.
I found information about this [here](https://jrsoftware.org/ishelp/index.php?topic=setup_uninstalldisplayname), but I didn't build it myself, since there was a problem in the process like in [this post](https://github.com/telegramdesktop/tdesktop/issues/16397#issuecomment-853729632).
=> Specify name of app in list of installed apps

CMakeLists.txt
Depends on https://github.com/desktop-app/cmake_helpers/pull/110
=> Allow to build with generators other than Xcode on mac

Telegram/SourceFiles/platform/linux/main_window_linux.cpp
When Wayland support for global menu was added (0b86feeeb58a0a5302a6811f0f51e97c562a7134), X11 support was broken since QWindow::winId returns WId what is a quintptr that expands to uint32 on 32-bit and to uint64 on 64-bit, while AppMenu d-bus service accepts only uint32.
=> Fix global menu on 64-bit systems with X11

.github/workflows/lock.yml
There's no need to call action so frequently
=> Lock issues once a day rather than once a hour

Telegram/CMakeLists.txt, Telegram/SourceFiles/boxes/edit_caption_box.cpp, Telegram/SourceFiles/boxes/send_files_box.cpp, Telegram/SourceFiles/history/history_widget.cpp, Telegram/SourceFiles/history/view/history_view_replies_section.cpp, Telegram/SourceFiles/history/view/history_view_scheduled_section.cpp, Telegram/SourceFiles/platform/linux/linux_gtk_integration.cpp, Telegram/SourceFiles/platform/linux/linux_gtk_integration.h, Telegram/SourceFiles/platform/linux/linux_gtk_integration_dummy.cpp, Telegram/SourceFiles/platform/linux/linux_gtk_integration_p.h, Telegram/SourceFiles/platform/linux/specific_linux.cpp, Telegram/SourceFiles/platform/mac/specific_mac.h, Telegram/SourceFiles/platform/platform_specific.h, Telegram/SourceFiles/platform/win/specific_win.h
Fixed in Qt by https://codereview.qt-project.org/c/qt/qtbase/+/306771
This reverts commit 3a91003eeacb038032499d60f3a47e3ef6e4c14f.
=> Revert "Use gtk clipboard when available to avoid https://bugreports.qt.io/browse/QTBUG-56595"

Telegram/SourceFiles/media/player/media_player_volume_controller.cpp, Telegram/SourceFiles/media/system_media_controls_manager.cpp
The audio mixer tracks changes to the volume using the settings:
https://github.com/telegramdesktop/tdesktop/blob/5000902d61d556960c4afe20f7624933fd914499/Telegram/SourceFiles/media/audio/media_audio.cpp#L588-L596
However it uses the internal value `_volumeSong` to set the volume, so if the setting is updated before the mixer value, the previous value is used.
When the slider value changes, the value in settings gets updated before the mixer value, causing the previous value to be used in the mixer, which causes #16276
Additionally, setting the volume with media controls only updates the setting, causing the playback volume to not change, which causes #16905
=> Fix song volume controls, closes #16276 #16905

Telegram/Resources/export_html/css/style.css
Fixes #16120.
`unicode-bidi: plaintext` makes browser auto-detect base bidi direction according to bidi algorithm heuristics, on each line separately.
https://drafts.csswg.org/css-writing-modes/#bidi-algo
AFAICT this matches both Android and Desktop behaviors, and is the friendly behavior for mixed-direction users.
Purely LTR users should not be affected — the heuristics return LTR even on "neutral" lines that contain no letters, only punctuation/emojis/digits.
(http://www.unicode.org/reports/tr9/#P2 — rule P3 defaults to level 0, which is LTR.)
Whereas all RTL language users in practice need to deal with mixed-direction texts, and the ability to split lines to prevent LTR/RTL mixups is extremely handy...
The `text-align: start` ensures LTR-detected lines are displayed left-aligned, and …
=> Export CSS: per-line automatic bidi direction

Telegram/SourceFiles/platform/linux/specific_linux.cpp
QApplication has a historical feature[1] of calling setlocale(3) at init,
which today cause more harm than good.  Such call isn't thread safe neither
per C standard, not per any known libc implementation.  The Gio threads
would call into locale reading functions all the time, so early access to
locale by Gio may race with setlocale() by Qt leading to undefined behavior.
Platform specific start before the Sandbox (aka QApplication) is at core
design of tdesktop and that order can't be changed. There is no way to pause
Gio until QApplication instantiates.
Fortunately, Qt library itself has a static global flag that prevents it
from calling setlocale() twice. We don't even need to instantiate a
temporary QCoreApplication, we can just call into the method.  So call
it form Platform::start …
=> Close a race between Gio threads and Qt application init.

Telegram/build/docker/centos_env/Dockerfile
The reason was to not to do a full rebuild, but looks like the cache is already cleaned
=> Move new dependencies to the beginning of Dockerfile, update patches

Telegram/build/docker/centos_env/Dockerfile
=> Build Qt without egl-extension-platform-wayland

Telegram/SourceFiles/platform/linux/specific_linux.cpp, snap/snapcraft.yaml
Together with pull requests to other components, tdesktop/dev compiles and works perfectly on FreeBSD.
https://github.com/telegramdesktop/libtgvoip/pull/35
https://github.com/desktop-app/tg_owt/pull/69
https://github.com/desktop-app/cmake_helpers/pull/123
Note: the zip.h problem, I believe, can show up on a certain Linux distributions as well. And of course won't show up on FreeBSD if zlib package isn't installed. In other words, it isn't actually related to the topic.
=> Couple small fixes to compile on FreeBSD

Telegram/CMakeLists.txt
When both minizip [1] and libzip [2] are present in the build
environment we have two <zip.h> includes. We are interested in
the minizip. Unfortunately, libzip usually installs its zip.h
straight into ${PREFIX}/include where lots of other headers reside.
We pick up ${PREFIX}/include into the include path with the
desktop-app::lib_base target, which is also dependency of
of tdesktop::td_* targets. To fix compilation in presence of
conflicting zip.h we need to put minizip's include directory
before ${PREFIX}/include, thus record its dependency before
all other dependencies that can bring desktop-app::lib_base.
[1] http://www.winimage.com/zLibDll/minizip.html
[2] https://libzip.org
=> Fix compilation in presence of libzip installed.

snap/snapcraft.yaml
Depends on https://github.com/desktop-app/snapcraft-desktop-helpers/pull/1
=> Backport fonts hook from snapcraft extensions

Telegram/SourceFiles/platform/win/specific_win.cpp
Fixes #3571 
If you want to test locally but don't want to uninstall maps - just change "bingmaps" to something unexisting in line 559
=> Open map in browser if default "bingmaps:" handler is not found

snap/snapcraft.yaml
Qt uses libOpenGL and libGLX instead of libGL now
=> Fix Qt dependencies in snap

Telegram/SourceFiles/core/sandbox.cpp
QScreen::logicalDotsPerInch can be overriden by QT_FONT_DPI what is not good
=> Use QPlatformScreen::logicalDpi instead of QScreen::logicalDotsPerInch

snap/snapcraft.yaml
Due to the removal of beariers, network-manager-observe shouldn't be needed anymore.
hardware-observe is needed for DeviceModelPretty, though.
Added systemd to stage-packages for calling systemd-detect-virt.
=> Adjust snap permissions

Telegram/build/prepare/prepare.py
Even though TDesktop build migrated to VS 2022, dependencies script still had "Visual Studio 16 2019" for mozjpeg and openal-soft as a generator. Removing these lines allows to use latest Visual Studio without changing the script.
=> Removed explicit definition of cmake generator

Telegram/build/prepare/prepare.py
On M1 mac, some dependencies build two `arm64` builds and makes `lipo` fail.
=> Add support to build on M1 Mac

Telegram/SourceFiles/core/utils.cpp
Deprecated function FIPS_mode_set() was removed in OpenSSL 3.0.
Switched to EVP_default_properties_enable_fips() as described in OpenSSL 3.0 migration guide.
Closes #17348.
=> Fixed build against OpenSSL 3.0

Telegram/SourceFiles/window/main_window.cpp
If the `QDrag` object is destroyed too early, drag and drop will not work on Linux, because communication will still have to happen later between source and target, see: https://freedesktop.org/wiki/Specifications/XDND/
This patch increases the lifetime of `drag`, by changing the type to a raw pointer. This does not create a memory leak, as parent is specified in the `QDrag` constructor, which will free it later.
If you know a better way to increase the lifetime of the `drag` and don't like this "Qt way" of memory management, let me know. :)
In any case this finally fixes Drag and drop on Linux.
=> Fix drag and drop on Linux

lib/xdg/telegramdesktop.desktop
Telegram is a single-instance app; attempting to open a second instance
fails and simply focuses the existing instance. However the app's
.desktop file does not indicate this to Linux desktop shells like GNOME
and KDE Plasma, causing them to show a "Start new instance/Open new
window" action for the app that will not work when used.
This commit fixes that by setting `X-GNOME-SingleWindow=true` in the
desktop file. This is a GNOME-specific key, but it is honored in KDE
Plasma too.
=> Mark as single-instance using X-GNOME-SingleWindow key

Telegram/SourceFiles/app.cpp, Telegram/SourceFiles/calls/group/calls_group_members.cpp, Telegram/SourceFiles/platform/linux/main_window_linux.cpp
A few warnings found when building tdesktop 3.3.0 on OpenBSD.
=> Fix -Wunused-const-variable variables

Telegram/SourceFiles/platform/linux/linux_desktop_environment.cpp, Telegram/SourceFiles/platform/linux/linux_desktop_environment.h, Telegram/SourceFiles/platform/linux/specific_linux.cpp
Variables can point to a mixed environment, make DE detection non-exclusive.
Remove unused methods.
=> Rework DE detection

lib/xdg/telegramdesktop.desktop
X-GNOME-SingleWindow was upstreamed to be an XDG spec with the name
"SingleMainWindow" in
https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/53
=> Change X-GNOME-SingleWindow key to SingleMainWindow

lib/xdg/telegramdesktop.desktop
`X-GNOME-SingleWindow` is best to be used for backward compatibility. Since `SingleMainWindow` was recently added, many Desktop Environments and Window Managers may not have it implemented yet.
=> Re-add `X-GNOME-SingleWindow`

lib/xdg/telegramdesktop.desktop
`SingleMainWindow` is a part of XDG SPEC version 1.5 and bogus on 1.0.
Closes #23879.
=> Updated XDG SPEC version to 1.5

Telegram/SourceFiles/core/launcher.cpp
This PR fixes https://github.com/telegramdesktop/tdesktop/issues/23877 .
After this change it should still default to xorg, like with Qt5, while respecting `QT_QPA_PLATFORM` if it is set.
=> Use QT_QPA_PLATFORM if provided.

Telegram/SourceFiles/history/admin_log/history_admin_log_item.cpp
Cause [GenerateParticipantChangeText](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/admin_log/history_admin_log_item.cpp#L470-L492) haven't handled `Restricted` to `Member` log, so admin or bot delete(remove) a user's exception.
You will see you're invited a user:
After new commit, admin log should be shown correctly.
I think `GenerateBannedChangeText` renamed to `GeneratePermissionsChangeText`, it would be more suitable, cause `Banned` and `Restricted >> Member` now sharing same method.
=> Fix incorrect admin log

snap/snapcraft.yaml
WebRTC no more supports PipeWire 0.2, so it's impossible to build PipeWire support until core22 runtime is released
=> Build WebRTC without PipeWire support in snap

changelog.txt
Currently, all 2022 releases appear as 2021 ones. Since the `changelog.txt` file is used to generate `<release>` tags in metainfo.xml for Linux, and appstream sorts releases by date, they end up in a wrong order: version 2.4.2 appears as first (latest). This causes Flatpak frontends (e.g. Flathub [web page](https://flathub.org/apps/details/org.telegram.desktop)) to show the wrong version for Telegram Desktop.
=> Correct year in changelog for 2022 releases

Telegram/SourceFiles/mainwindow.cpp
Unnecessary minimize triggers animation that provides a sign there were a window. There's also seem to be queuing of hide on Linux that makes the effect even more noticable and it seems the bug this workaround was made for no longer reproduces.
=> Hide the window instantly within autostart

Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp, Telegram/SourceFiles/ffmpeg/ffmpeg_utility.h, Telegram/SourceFiles/media/audio/media_audio_capture.cpp, Telegram/SourceFiles/media/audio/media_audio_ffmpeg_loader.h, Telegram/SourceFiles/media/streaming/media_streaming_file.cpp
It has been released on January 17th. This patch keeps source compatibility with older versions.
See also: https://github.com/TelegramMessenger/tgcalls/pull/14
=> Fix build against FFmpeg v5.0

Telegram/SourceFiles/history/history_inner_widget.cpp, Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
This fixes notifications not being cleared from history on Linux, once the chat with that person (whom the notifications originated from) is opened.
The notification reference must only be removed when the notification is really cleared - and not already when the notification has timed out.
See commit message for more details.
=> [Linux] Clear read message notifications from history

Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
QWindow::screen seem to be buggy on Windows and doesn't always follow window moves
=> Get media viewer screen by checking the screen by active window position

Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
1. FramelessWindowHint seem to be a redudant leftover of BypassWindowManagerHint, media viewer uses fullscreen state now that implies lack of the frame
2. MaximizeUsingFullscreenGeometryHint is useless since media viewer doesn't use maximize
3. Transient parent/window modality dance is replaced with minimum/maximum size just like in other places where tiling shouldn't be done
4. setWindowState(WindowFullScreen) is replaced with showFullScreen that ensures the flag is set on each show
=> Update media viewer window flags

Telegram/SourceFiles/platform/linux/specific_linux.cpp
=> Implement org.freedesktop.appearance.color-scheme

snap/snapcraft.yaml
It's required by webkit2gtk for correct operation
=> Add glib-networking to snap

Telegram/build/docker/centos_env/Dockerfile
Use --depth=1 for submodules, too.
This also replaces perl init-repository for Qt as the only thing it does is fetches submodules, but there's no way to specify --depth=1 with it.
=> Speed up submodule checkout in Dockerfile

Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
This could be a regression for tiling WMs, though...
Fixes #24416
=> Fix media viewer on Unity

Telegram/SourceFiles/api/api_media.cpp, Telegram/SourceFiles/boxes/peers/edit_peer_reactions.cpp
More info:
https://github.com/telegramdesktop/tdesktop/issues/24385
fixes #24014
https://github.com/ericniebler/range-v3/issues/1691
=> Explicitly specify QVector element type to fix build with clang13+qt6

Telegram/SourceFiles/calls/group/ui/desktop_capture_choose_source.cpp, Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
This partially reverts commit e5d8a1aa3c9457c0c0ceb560190a19d7b5349d9d to use QWindow::setScreen.
=> Partially revert "Use QWidget::screen/QWidget::mask instead of QWindow ones"

Telegram/SourceFiles/data/data_types.h
Build for RISC-V architecture using v4.0 release will fail with errors:
```
/build/telegram-desktop/src/tdesktop-4.0.0-full/Telegram/SourceFiles/data/data_types.h:152:31: error: enumerator value ‘-2’ is outside the range of underlying type ‘char’
152 |         FileDownloadFailed = -2,
|                               ^
/build/telegram-desktop/src/tdesktop-4.0.0-full/Telegram/SourceFiles/data/data_types.h:153:29: error: enumerator value ‘-1’ is outside the range of underlying type ‘char’
153 |         FileUploadFailed = -1,
|                             ^
ninja: build stopped: subcommand failed.
```
Reference to C++ standard ([cppref](https://en.cppreference.com/w/cpp/language/types#Character_types)):
> `char` - type for character representation which can be most efficiently processed on …
=> Explicitly specify `signed` modifier for `char` type

.github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/win.yml
Documentation is not sourced in actions since prepare.py invention
=> Don't trigger actions on build documentation change

Telegram/SourceFiles/media/audio/media_audio.cpp
This commit significantly improves the usability of the volume controls
for controlling volume in a way that matches intuitively onto human
needs and loudness perception.
Using the third power of the volume is a good approximation of the
quasi-logarithmic psychoacoustic system, while being defined everywhere
and preserving the useful quality of 0% volume mapping onto gain 0.0.
The use of this exact mapping function is a prior art established by
e.g. PulseAudio, among many other programs.
Fixes #24488
=> Use quasi-logarithmic volume controls

Telegram/SourceFiles/platform/linux/linux_xdp_open_with_dialog.cpp
glib shows a warning about invalid GVariant and empty activation_token shouldn't hurt I believe
=> Always pass activation_token option

Telegram/SourceFiles/boxes/premium_preview_box.cpp, Telegram/SourceFiles/boxes/reactions_settings_box.cpp, Telegram/SourceFiles/settings/settings_premium.cpp, Telegram/SourceFiles/ui/text/custom_emoji_instance.cpp
Telegram/SourceFiles/ui/text/custom_emoji_instance.cpp:23:16: warning: unused variable 'kMaxFrameDuration' [-Wunused-const-variable]
Telegram/SourceFiles/boxes/reactions_settings_box.cpp:46:16: warning: unused variable 'kVisibleButtonsCount' [-Wunused-const-variable]
Telegram/SourceFiles/boxes/premium_preview_box.cpp:53:16: warning: unused variable 'kShiftDuration' [-Wunused-const-variable]
Found by:	clang
=> Fix warnings by removing unused variables

Telegram/SourceFiles/media/view/media_view_pip.cpp, Telegram/SourceFiles/media/view/media_view_pip.h
During testing with Qt 6.4 I now remember why I made a way complicated logic (yes, because the trivial one bugs with Qt 6.4)
This restores it, but uses event filters rather than hardware integration override
=> Handle PiP aspect ratio on Wayland synchronously

Telegram/SourceFiles/ffmpeg/ffmpeg_frame_generator.cpp, Telegram/SourceFiles/media/audio/media_audio_capture.cpp, Telegram/SourceFiles/media/audio/media_audio_ffmpeg_loader.cpp, Telegram/SourceFiles/media/audio/media_audio_ffmpeg_loader.h, Telegram/SourceFiles/media/clip/media_clip_ffmpeg.cpp, Telegram/SourceFiles/media/clip/media_clip_ffmpeg.h, Telegram/SourceFiles/media/streaming/media_streaming_file.cpp, Telegram/SourceFiles/media/streaming/media_streaming_file.h
FFmpeg docs say that you must return `AVERROR_EOF` from the read callback, not zero. Still, Telegram just propagates the return value from `IODevice::read()` call, which returns zero in case of EOF.
I don't know whether this commit has any effect on the upstream build, but it fixes a bug in Debian build of Telegram, which is using FFmpeg 5.1 instead of 4.4. Still, it's also useful in the upstream, as it makes work with FFmpeg more correct.
=> Correct FFmpeg API usage

Telegram/SourceFiles/platform/linux/launcher_linux.cpp, Telegram/SourceFiles/platform/linux/specific_linux.cpp
It depends on Core::UpdaterDisabled that is not initialized in Launcher::initHook yet
=> Move QGuiApplication::setDesktopFileName call to Platform::start

snap/snapcraft.yaml
This is reported as fixed in snapcraft, thus these paths should be set automatically
=> Remove explicit setting of paths for cmake in snapcraft.yaml

snap/snapcraft.yaml
gtk-common-themes contains all the themes now
=> Get rid of legacy themes in snap

Telegram/SourceFiles/core/file_utilities.cpp
This makes first download to go to temp directory, but I can't think of better solution without changing download path getting architecture.
Fixes #25279
=> Fix crash when asking download path in sandbox environment

Telegram/SourceFiles/settings/settings_experimental.cpp, Telegram/SourceFiles/ui/cached_round_corners.cpp, Telegram/SourceFiles/ui/chat/chat_style.cpp, Telegram/SourceFiles/ui/chat/chat_style.h, Telegram/SourceFiles/ui/chat/chat_style_radius.cpp, Telegram/SourceFiles/ui/chat/chat_style_radius.h, Telegram/SourceFiles/ui/chat/message_bubble.cpp, Telegram/SourceFiles/window/themes/window_theme_preview.cpp, Telegram/cmake/td_ui.cmake
This toggle allows switching to the pre-4.3.0, smaller message bubble radius after an app restart. The message bubble radius styles now have to be referenced via the `Ui::BubbleRadius*` and `Ui::MsgFileThumbRadius*` wrappers to use the appropriate value.
=> Add an experimental "small message radius" toggle

Telegram/SourceFiles/media/system_media_controls_manager.cpp
And let it use service name provided by flatpak by default
Depens on https://github.com/desktop-app/lib_base/pull/140
=> Update to changes in MPRIS SystemMediaControlsManager backend

Telegram/SourceFiles/platform/linux/specific_linux.cpp
Snap reports it as present, but prevents the access and GNotification attempts to use portal that doesn't work in snap
=> Ensure GNotification is not autodetected in snap

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp, Telegram/SourceFiles/platform/linux/specific_linux.cpp, Telegram/SourceFiles/platform/platform_specific.cpp
The UX is not the best without sound, so there's no advantage in using GNotification on GNOME.
Remove mention about being native to GNOME as it's not true anymore.
=> Use GNotification only in flatpak by default

.github/workflows/linux.yml
The binary is stripped anyway, there's no sense in producing debug symbols
=> Speed up Linux action

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
All modern notification daemons have support for the default action and it's a requirement with the portal spec
=> Don't show reply button in Linux native notifications when it's not supposed to

Telegram/SourceFiles/boxes/translate_box.cpp
TDesktop provides support for many languages for translating, it is already possible to translate from Esperanto, but unfortunately it lacks support for translating to Esperanto. This simple pull request will fix that.
I tested on Android and iOS, there I am able to translate to Esperanto:
=> Add Esperanto to language list of translate box

Telegram/SourceFiles/boxes/translate_box.cpp
Port from gentoo: https://github.com/gentoo/gentoo/blob/f62d7c6599bbb275f7863bd1fef0f5d31a673703/net-im/telegram-desktop/files/tdesktop-4.3.4-fix-disabling-spellcheck.patch
/var/tmp/portage/net-im/telegram-desktop-4.3.4/work/tdesktop-4.3.4-full/Telegram/SourceFiles/boxes/translate_box.cpp:18:10: fatal error: spellcheck/platform/platform_language.h: No such file or directory
18 | #include "spellcheck/platform/platform_language.h"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
=> Fix building without spellcheck

Telegram/SourceFiles/platform/linux/specific_linux.cpp
=> Don't use unneeded QEventLoop::ApplicationExec

Telegram/SourceFiles/platform/linux/specific_linux.cpp
tdesktop defaults to (probably requires) C++20, but `std::result_of`[0]
was deprecated in C++17 and removed in C++20.
0: https://en.cppreference.com/w/cpp/types/result_of
=> Use std::invoke_result_t not ::result_of to fix C++20 tdesktop 4.3.4

Telegram/ThirdParty/minizip/crypt.h, Telegram/ThirdParty/minizip/ioapi.c, Telegram/ThirdParty/minizip/ioapi.h, Telegram/ThirdParty/minizip/unzip.c, Telegram/ThirdParty/minizip/unzip.h, Telegram/ThirdParty/minizip/zip.c, Telegram/ThirdParty/minizip/zip.h
https://github.com/madler/zlib/releases/tag/v1.2.13
Tested with tdesktop 4.4.1 on OpenBSD/amd64, where a manual fix is still
required to build tdesktop's old zlib version:
https://github.com/openbsd/ports/blob/master/net/tdesktop/Makefile#L105-L108
I upstreamed this fix with https://github.com/madler/zlib/pull/678,
although it got fixed differently in
https://github.com/madler/zlib/commit/40c5a9bc06c5b0746aab270971c8cc546e3d5fc7
=> Update to minizip 1.2.13

Telegram/SourceFiles/data/data_photo_media.cpp
I tested it for, a day, and it looks good enough for me.  I honestly don't see the reason why we would like to downscale them here. 
If we receive 2560px image, we display it as 2560px image. Images sent from tdesktop are still downscaled to 1280px. This behavior is consistent with other telegram clients.
Fixes #2206
=> removed downscaling 2560px images before displaying them - #2206

Telegram/SourceFiles/storage/storage_media_prepare.cpp, Telegram/SourceFiles/ui/chat/attach/attach_extensions.cpp, Telegram/SourceFiles/ui/chat/attach/attach_extensions.h
The code path when choosing an image in file dialog tries to read a QImage with Images::Read and then only checks that mime type starts with image/ in ValidPhotoForAlbum
Core::FileIsImage and QImageReader::canRead checks should provide the same behavior
=> Use the same check for drag'n'drop image type as for file dialog

Telegram/SourceFiles/storage/localimageloader.cpp, Telegram/build/docker/centos_env/Dockerfile, Telegram/build/prepare/prepare.py
Qt had a bug with interpreting PNG gamma, but it seems it's fixed now.
=> Remove force-disabling of Qt's color space support for sent images

Telegram/SourceFiles/core/file_utilities.cpp
It was batch replaced as part of 7b5781b84573ba02cf968b093fa37f23c6b4cb3f, but it's not really semantically valid
=> Don't involve locale in filename timestamp generation

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp, Telegram/SourceFiles/settings/settings_experimental.cpp, Telegram/SourceFiles/window/notifications_manager.cpp
GApplication will always be used on Linux now. GNotification gets a toggle instead.
=> Get GApplication out of experimental settings

Telegram/SourceFiles/core/application.cpp
To avoid system dialog being under it
=> Call scheme handler registration after opening main window

Telegram/SourceFiles/platform/linux/specific_linux.cpp
This ensures possible warnings use right process name
=> Set prgname and application name before glibmm initialization

Telegram/SourceFiles/core/application.cpp, Telegram/SourceFiles/platform/linux/specific_linux.cpp, Telegram/SourceFiles/platform/mac/specific_mac.h, Telegram/SourceFiles/platform/platform_specific.h, Telegram/SourceFiles/platform/win/specific_win.h, Telegram/SourceFiles/settings/settings_codes.cpp
Just like AppUserModelId on Windows
This makes the cheat code and having the function outside of private namespace unnecessary
=> Install launcher on every launch on Linux

Telegram/SourceFiles/media/audio/media_audio.cpp
This makes no effective change for openal-soft as alGetEnumValue and alcGetEnumValue do lookup in the same table, but it's more semantically right and openal-soft is not the only implementation of the API
=> Don't use alcGetEnumValue for non-ALC enum value

Telegram/SourceFiles/settings/settings_main.cpp
This is less confusing in multi-monitor environments
Makes #25856 less confusing
=> Use window widget's devicePixelRatio when displaying interface scale value

Telegram/SourceFiles/export/output/export_output_file.cpp
Removed deprecated GSL headers usage.
The following PRs need to be merged first:
- https://github.com/desktop-app/lib_rpl/pull/4
- https://github.com/desktop-app/lib_base/pull/156
- https://github.com/desktop-app/cmake_helpers/pull/252
Closes #25870.
=> Removed deprecated GSL headers usage

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp, Telegram/SourceFiles/platform/linux/specific_linux.cpp
That's a much better way to avoid defunct event loop that will work in any edge case
Also don't assume GApplication is always running in Platform::Notifications::Enforced
=> Don't hold GApplication

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp, Telegram/SourceFiles/platform/linux/specific_linux.cpp
As there are notification daemons with quick reply support and GNotification API having mandatory default action support now, it's the time to reconsider button arrangement.
This also makes it possible for legacy notification daemons without default action support opening the chat when no buttons are allowed since 05524c3f6c5a1a4688ed111b51317970b22fac8e again.
=> Deduplicate notification actions on Linux

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
There are labels for this purpose, pre-defined title lets people to not to think about the title what leads to feature requests not having title
=> Remove pre-defined title from feature request template

snap/snapcraft.yaml
Both glib 2.76 and Qt 6.5 detect snap automatically now
=> Don't set no more needed variables for portal support in snap

Telegram/SourceFiles/api/api_chat_filters.cpp, Telegram/SourceFiles/boxes/filters/edit_filter_links.cpp, Telegram/SourceFiles/settings/settings_folders.cpp, Telegram/SourceFiles/window/window_filters_menu.cpp
Same story as 2b383a4 for #24014.
Fixes 4.8.0 build on OpenBSD/amd64 7.3 with clang 13.0.0, range-v3 0.12.0 and Qt 6.5.0.
=> Explicitly specify QVector element type to fix build with clang13+range-v3+qt6

Telegram/build/docker/centos_env/Dockerfile
This seem to make some miscompilation that lead to hangs
=> Get rid of -Ofast on Linux

snap/snapcraft.yaml
snap: connect to the network-bind interface, necessary on systems where desktop-legacy isn't supported like Ubuntu Core Desktop.
=> snap: connect to the network-bind interface

snap/snapcraft.yaml
Looks like having gsettings in global plugs is no more valid
=> Fix a warning in snap build

Telegram/build/docker/centos_env/Dockerfile, snap/snapcraft.yaml
So that Linux build uses same versions like Windows build.
=> Upgrade dav1d, libde265, libheif, libjxl

Telegram/SourceFiles/platform/linux/integration_linux.cpp, Telegram/SourceFiles/platform/linux/main_window_linux.cpp, Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp, Telegram/SourceFiles/platform/linux/specific_linux.cpp, Telegram/build/docker/centos_env/Dockerfile, snap/snapcraft.yaml
The Qt documentation says:
This is the file name, without the full path or the trailing ".desktop" extension of the desktop entry that represents this application according to the freedesktop desktop entry specification.
Qt 6.5.2 also automatically fixes it breaking all the current tdesktop and desktop-app usage expecting the file extension.
Depends on https://github.com/desktop-app/lib_base/pull/185, https://github.com/desktop-app/lib_webview/pull/41
=> Fix QGuiApplication::desktopFileName usage

Telegram/SourceFiles/platform/linux/specific_linux.cpp
Working dir not set leads to unrelevant instance being launched with unrelevant bus name and entire launchf fails.
D-Bus service files also don't need backslash escaping unlike the .desktop files.
=> Fix D-Bus service with non-standard workdir or backslash in the path

Telegram/SourceFiles/platform/mac/main_window_mac.mm
ui_window_mac has logic depending on Qt version to use Metal when possible, this will conflict once Qt is updated to 6.4+
=> Get rid of QOpenGLWidget in main_window_mac

Telegram/build/docker/centos_env/Dockerfile
This API sadly not present on older systems and we have to use the thread unsafe one if we want to be compatible with them
Fixes #26658
=> Downgrade libwayland to the version before thread safe API was introduced

Telegram/SourceFiles/platform/linux/integration_linux.cpp, Telegram/build/docker/centos_env/Dockerfile
This makes the behavior consistent and is possible now thanks to a Qt patch
Depends on https://github.com/desktop-app/patches/pull/149
Fixes #26461
Relates to #26370
=> Make dark mode update go through Qt code on Linux

Telegram/SourceFiles/platform/linux/integration_linux.cpp
g_dbus_connection_signal_subscribe calls the callback on the same thread
=> Don't use crl::on_main unnecessarily with XDP::SettingWatcher

Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
This is fixed in xdg-desktop-portal 1.17.
There's no way to check xdg-desktop-portal version so it's either not having support for passing last used path at all in sandbox or encountering the bug on old systems.
=> Get rid of sandboxed paths workaround

Telegram/SourceFiles/core/application.cpp
=> Avoid Windows-specific hack to ruin initial main window geometry on Linux

Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp, Telegram/SourceFiles/media/view/media_view_pip.cpp, Telegram/cmake/lib_prisma.cmake
We need to workaround getting the actual screen for the parent by getting its position yet we need to get the setted screen for the widget itself as that's the screen used to compute the geometry
Fixes #26952
=> Fix getting the screen of viewer/pip

.github/workflows/mac_packaged.yml
This ensures the same versions of packages between GitHub runners at a point in time
=> Update brew packages in macOS packaged action

Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp
This fixes issue #26917 when the client crashed playing a video with a non-standard SAR (pixel size) due to an incorrect calculation of the video width, it was -1034
=> Fix crash on some videos

Telegram/SourceFiles/boxes/gift_premium_box.cpp, Telegram/SourceFiles/core/core_settings.cpp
Building with /WX fails on VS 17.8.3 because of warning C4805 (unsafe type mixing). This happens because numeric value assigned to variables in question instead of boolean.
This PR fixes the warning in two places where it happens.
=> Fix warning C4805

snap/snapcraft.yaml
So the Canonical builders build on new architectures as soon as they appear
=> Get rid of architecture whitelist from snapcraft.yaml

Telegram/SourceFiles/core/sandbox.cpp
Reading system proxy on Linux reads to massive crashes in system libraries.
Since those crashes are unreproducible in development environment, it's not possible to find the root cause.
Workarounds #27482.
=> Disable system proxy support on Linux

snap/snapcraft.yaml
Looks like cppgir has stopped to use it during some of the updates
=> Remove no longer needed boost-program-options from snap

Telegram/build/prepare/prepare.py
Fix libvpx build on VS 17.8+
used with https://github.com/desktop-app/patches/pull/182
Fixes #26012
i haven't updated commit point in snap & docker because they were on different sha from prepare.py and they don't need this fix.
=> Fixes #26012 libvpx build on VS 17.8+ 

Telegram/build/prepare/linux.sh
I was having problems when running the script with zsh. Adding a bash shebang avoids that.
```
./Telegram/build/prepare/linux.sh: 3: pushd: not found
```
=> add bash shebang

Telegram/build/prepare/prepare.py
Incorrect setting env variable leads to incorrect build command line for libjxl (windows, see failing actions in github)
was, note quotes. 
All those arguments passed as single argument to cmake.
```
Telegram\build\prepare> SET cmake_defines="-DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_FUZZERS=OFF -DJPEGXL_ENABLE_DEVTOOLS=OFF -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_DOXYGEN=OFF -DJPEGXL_ENABLE_MANPAGES=OFF -DJPEGXL_ENABLE_EXAMPLES=OFF -DJPEGXL_ENABLE_JNI=OFF -DJPEGXL_ENABLE_JPEGLI_LIBJPEG=OFF -DJPEGXL_ENABLE_SJPEG=OFF -DJPEGXL_ENABLE_OPENEXR=OFF -DJPEGXL_ENABLE_SKCMS=ON -DJPEGXL_BUNDLE_SKCMS=ON -DJPEGXL_ENABLE_VIEWERS=OFF -DJPEGXL_ENABLE_TCMALLOC=OFF -DJPEGXL_ENABLE_PLUGINS=OFF -DJPEGXL_ENABLE_COVERAGE=OFF -DJPEGXL_ENABLE_PROFILER=OFF -DJPEGXL_WARNINGS_AS_ERRORS=OFF" …
```
=> Fix libjxl windows build

Telegram/build/prepare/prepare.py
Explicitly disable brotli in QT build.
It was accidentally brought in by libjxl and leads to unresolved symbol linker errors on Mac
Fixes #27560
=>  Fix Mac build (disable qt_feature_brotli)

docs/building-mac.md
https://raw.githubusercontent.com/Homebrew/install/master/install returns 404
I've provided a correct url, just not sure why use `/bin/bash -c` instead of `ruby -e`
=> Update mac build instructions with up-to-date homebrew link

Telegram/build/prepare/prepare.py
Could be merged instead of #27585, as it tries to resolve the same problem: fixed thread count in Qt build. This PR resloves the problem by using the `%NUMBER_OF_PROCESSORS%`.
However, it should be known that it could return wrong value: https://learn.microsoft.com/en-us/troubleshoot/windows-server/setup-upgrade-and-drivers/number-of-processors-environment-variable-show-incorrect-values
=> Use %NUMBER_OF_PROCESSORS% for jom

Telegram/Resources/iv_html/page.css
To ensure that IV looks good enough on different platforms, the system font stack is used.
It's taken from https://systemfontstack.com/ with some tweaks:
- Tahoma is used before Arial, since Tahoma was widely used in Windows before Segoe UI was introduced (not sure if it matters, since Windows 7 includes Segoe UI anyway, and earlier OSes are not supported);
- Georgia font is used before Times New Roman as it was used in IV before this PR (and it looks better than Times New Roman);
- Cascadia Code is used before Consolas, since it's new Microsoft's font that is used primarily in Windows Terminal.
=> Using system font stack for Instant View

Telegram/Resources/iv_html/page.css
This PR adds the Windows 11 version of the Segoe UI font to the Instant View stylesheet
=> Add new Segoe UI font to IV css

Telegram/build/docker/centos_env/Dockerfile
These are the same versions like the Windows build ( updated in https://github.com/telegramdesktop/tdesktop/commit/4abc68ab1c987e856f09d6d08672abc23f1bd6d0 )
=> Upgrade dav1d, libavif, libde265, libheif on Linux

Telegram/SourceFiles/mainwindow.cpp
There's a yet another another visility state called "exposed" and the window could be unexposed while being not hidden and not minimized.
When the window is unexposed, Qt doesn't draw and the user can't see changes for sure.
=> Don't mark as read when unexposed

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
7.5-current with clang 16.0.6 and Qt6 fails, not entirely sure why...
=> Fix tdesktop 4.15.6 build on OpenBSD

Telegram/SourceFiles/data/data_document_resolver.cpp
The correct python zipapp extension on windows is pyzw, this typo could lead to executing code in the client device without proper warning
=> Fixed python zipapp extension on windows in IsExecutableName

Telegram/build/prepare/prepare.py
Fixes MacOS actions on GH
Problem is
libavif - finds libsharpyuv library v1.4.0 (available on github worker) and uses it for build.
libwebp - builds libsharpyuv from libwebp repo (v1.3.1)
then libsharpyuv v1.3.1 is used in the Telegram build.
That feature is not used in kimageformats plugin and if it will be used, it can be used only during encoding.
AVIF plugin is used only for decoding AVIF anyway.
=> Don't use/link libsharpyuv in libavif

Telegram/SourceFiles/core/crash_report_window.cpp
This should prevent nested crashes when loading custom fonts
=> Switch crash reporter to system fonts

Telegram/SourceFiles/lang/lang_instance.cpp
isTagChar seems to check for alphanumeric + ```_``` input, but would accept extra ```[, ], ^, '``` because of typo
=> Fixing typo

snap/snapcraft.yaml
Noble has libvpx9, not vpx8.
https://packages.ubuntu.com/search?keywords=libvpx9
=> fix: Incorrect package name

Telegram/build/docker/centos_env/Dockerfile, snap/snapcraft.yaml
This reverts commit b246328dcf96dfd44e11bef5932b8ff3d7deac5e.
=> Revert "Use latest mesa in snap"

Telegram/build/prepare/prepare.py
After using openssl3, I found that compiling on windows is very slow. nmake still does not seem to support parallel make, but we can use jom to enable multi-core compilation to speed up
[refer to](https://github.com/openssl/openssl/issues/9931)
=> Use jom build openssl on windows

docs/building-linux.md
Added double quotes to work correctly with spaces in current directory's name
Used [script](https://stackoverflow.com/a/4424334/9145106) in directory with name "/home/gooddok/test or not" to count number of arguments passed to the command, hope that's enough.
Before (13 arguments):
```
gooddok@ubuntu:~/test or not$ ./script.sh run --rm -it -v $PWD:/usr/src/tdesktop tdesktop:centos_env /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh -D TDESKTOP_API_ID=YOUR_API_ID -D TDESKTOP_API_HASH=YOUR_API_HASH
The number of arguments is: 13
The total length of all arguments is: 205: 
The length of argument 'run' is: 3
The length of argument '--rm' is: 4
The length of argument '-it' is: 3
The length of argument '-v' is: 2
The length of argument '/home/gooddok/test' is: 18
The length of …
```
=> Fix #25202: surrounding $PWD with double quotes

Telegram/SourceFiles/payments/ui/payments_panel.cpp, Telegram/SourceFiles/ui/chat/attach/attach_bot_webview.cpp, Telegram/build/docker/centos_env/Dockerfile, snap/snapcraft.yaml
Setting window flags may lead to native window being re-created
=> Ensure window flags are set before calling SeparatePanel::setInnerSize

Telegram/SourceFiles/core/file_utilities.cpp, Telegram/SourceFiles/platform/linux/file_utilities_linux.cpp
- Open it with O_CLOEXEC
- Remove unneseccary std::array complication
- Rely on Gio::UnixFDList to close it
=> File descriptor fixes for XDPOpenWithDialog

Telegram/SourceFiles/core/mime_type.cpp
`xlsb` is Excel's binary file format. `xlsb` files support macros similar to `xlsm`. 
Since `xlsm` is included in the list of executable file extensions, `xlsb` probably should be included too.
=> Add xlsb to list of executable extensions

Telegram/SourceFiles/boxes/download_path_box.cpp, Telegram/SourceFiles/core/application.cpp, Telegram/SourceFiles/core/application.h, Telegram/SourceFiles/export/view/export_view_settings.cpp, Telegram/SourceFiles/settings/settings_chat.cpp
=> Fix default export directory in flatpak

lib/xdg/org.telegram.desktop.metainfo.xml
In flathub, and it's front-ends like KDE's Discover or GNOME Software, Telegram shows "By John Preston", and some users were hesitant to install it afraid that was "fake", so i changed it to Telegram, this would also make it consistent with snap, thanks!
=> Changed dev name in org.telegram.desktop.metainfo.xml

Telegram/SourceFiles/lang/lang_values.h
Fixes #28283.
For more info see https://github.com/llvm/llvm-project/pull/80801.
Also can be fixed by using -Wno-missing-template-arg-list-after-template-kw
https://clang.llvm.org/docs/DiagnosticsReference.html#wmissing-template-arg-list-after-template-kw
=> Fix build with clang 19.1.0.

Telegram/Resources/export_html/css/style.css, Telegram/SourceFiles/export/data/export_data_types.cpp, Telegram/SourceFiles/export/data/export_data_types.h, Telegram/SourceFiles/export/export_api_wrap.cpp, Telegram/SourceFiles/export/export_api_wrap.h, Telegram/SourceFiles/export/output/export_output_html.cpp, Telegram/SourceFiles/export/output/export_output_json.cpp
This should allow to export reactions in both JSON and HTML exports. Fixes #27971
Tested in a local environment.
Current limitations in HTML output:
- Not rendering userpics. Only initials. As far as I understand, chat messages also don't render userpics.
- Not rendering custom emojis. It looks like there is no existing way to render them in HTML output and in messages they are not rendered as well. But instead, simple emoji alternative is rendered. Unfortunately, for reactions there is no simplified emoji provided. Thus, it is not possible to render custom emojis. As a placeholder I added "(custom emoji)".
Example JSON message with reactions:
```
{
"id": 112233,
"type": "message",
...
"reactions": [
{
"type": "emoji",
"count": 1,
"emoji": "😁",
"recent": [
{
"from": "Jane Smith", …
```
=> Add reactions to export chat history

Telegram/SourceFiles/ui/webview_helpers.cpp
=> fix(ui/webview_helpers): prepend 0 if color channel value is 1 char long

Telegram/SourceFiles/ui/controls/round_video_recorder.cpp
=> Fix some ffmpeg 7.x related errors

Telegram/build/setup.iss
While compiling installer with Inno Setup Compiler, this warning appeared:
> Warning: Architecture identifier "x64" is deprecated. Substituting "x64os", but note that "x64compatible" is preferred in most cases. See the "Architecture Identifiers" topic in help file for more information.
This pull request fixes this warning according to [Inno Setup Docs page](https://jrsoftware.org/ishelp/index.php?topic=archidentifiers).
=> Replace deprecated x64 architecture identifier

Telegram/SourceFiles/data/data_peer_bot_commands.cpp
Certain bots do not show commands in particular groups at random. This is a known issue, see e.g. #25027, #26735.
The issue is that we try to assign a value through an iterator even after we have called `remove`. This will cause the iterator to point to some other element, and then we copy an empty list of commands into that other list. This means that the bot list of some other bot, that is the bot with the next higher user ID, gets cleared instead.
This fixes the bug by making sure that we do not try to assign anything after calling `remove`.
=> Fix bug in ChatBotCommands::update when commands empty

Telegram/build/docker/centos_env/Dockerfile, Telegram/build/prepare/prepare.py, snap/snapcraft.yaml
kimageformats - contains tiny fix for animated JXL images
libheif - newer version supports images from latest iPhones. Note: 1.18.2 is not newest today, but I consider it better choice now than v1.19.5, which has lot of new features and maybe needs more time to test.
libjxl - update with relatively important fixes/improvements (CVE-2024-11498, avoiding abort in release build).
=> Update kimageformats, libheif, libjxl

Telegram/SourceFiles/platform/linux/specific_linux.cpp
Right now it checks the title controls layout that is typically set only by gtk based DEs and KDE matching the GNOME's and Pantheon's defaults.
There are more and more reports about window manager not to supporting both tray and minimization out of the box and title controls layout seem to typically be either unset or set to nothing leaving users with no way to run tdesktop with no window open.
=> Expand "always run in background" behavior from GNOME/Pantheon to all Linux

Telegram/SourceFiles/export/output/export_output_json.cpp
=> Don't export a duplicate "text" field on star gift

Telegram/SourceFiles/window/notifications_manager_default.cpp
Previously, notifications disappearing under cursor (e.g., because closed manually or open from another device) did not notify the manager properly, as the leaveEventHook was not triggered. This could lead to notifications staying around when not supposed to (see #28813).
This commit fixes that by explicitly notifying manager when the notification widget disappears under the cursor.
Fixes #28813.
=> Fix handling of notification disappearing under cursor

Telegram/SourceFiles/export/output/export_output_json.cpp
I hope this suggestion could be classified as "fixing the existing user experience" and therefore considered.
Currently it is possible to include various media types and set a size limit. But it's impossible to predict how much size and time the export will take, and how much data was below and above the limit.
This change saves media sizes even for skipped items, so allows to get this insights.
I've tested my change:
```json
{
"id": 111,
"type": "message",
"date": "2025-01-30T14:53:04",
"date_unixtime": "1738245184",
"from": "",
"from_id": "",
"photo": "(File not included. Change data exporting settings to download.)",
"photo_size": 178404,
"width": 960,
"height": 1280,
"text": "",
"text_entities": []
}
```
=> Include media sizes to exports

Telegram/SourceFiles/window/notifications_manager_default.cpp, Telegram/SourceFiles/window/notifications_manager_default.h
In this PR, for `Window::Notification::Default::internal::Widget` I:
- Rename `.isShowing()` to `.isFadingIn()` to clarify its behavior;
- Add a call to `Ui::Animations::Simple::stop` before `::start` in notification hiding animation.
~~Is blocked by desktop-app/lib_ui#254~~. Fixes #28811.
Kindly, see the commit messages for details.
=> Fix notifications when passed through with a cursor too quickly

.devcontainer.json
It's controlled by cmake.exportCompileCommandsFile and defaults to true
=> Don't set CMAKE_EXPORT_COMPILE_COMMANDS via cmake.configureSettings

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
This has no sense as QByteArray is CoW
=> Don't wrap QByteArray into std::shared_ptr

snap/snapcraft.yaml
It's not really needed for a long time
=> Remove fmt from snap

Telegram/build/docker/centos_env/Dockerfile
They were disabled due to -Ofast but Dockerfile is switched to -O3 since a long time
=> Re-enable ffmpeg optimizations on Linux

Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp, Telegram/SourceFiles/media/audio/media_audio_local_cache.cpp, Telegram/SourceFiles/ui/controls/round_video_recorder.cpp
Tested against ffmpeg 4.4.5 and 6.1.2 though there may be versions in between where this breaks. Fixes #28660.
=> Fix building against ffmpeg-4.x

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
It was added to replicate NotificationData::close but lots of places call it after the notification is already cleared
=> Clean up unnecessary calls to Manager::Private::clearNotification

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
Or it gets executed after hints.end() which clears hints
=> Move hints.lookup_value() out of xdg_notifications_notifications_call_notify

Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp
Now that notification closing happens in destructor, the iterator is no more needed
=> Use flat_map::remove in clearFrom{Topic,Item}

Telegram/SourceFiles/platform/linux/tray_linux.cpp, Telegram/SourceFiles/platform/linux/tray_linux.h
The code goes through Qt abstractions which not necessarily go through XEmbed
=> Get rid of XEmbed mentions

Telegram/SourceFiles/platform/linux/specific_linux.cpp
Looks like it broke through rebases
=> Fix Platform::ApplicationIconName for snap

Telegram/build/docker/centos_env/Dockerfile, Telegram/build/prepare/prepare.py, snap/snapcraft.yaml
I'm one of the authors of ada-url. I realized that telegram is using an old version of Ada, and wanted to contribute the following change to Telegram. The only major change I added was adding "ADA_INCLUDE_URL_PATTERN" flag which removes the URLPattern implementation, which Telegram doesn't depend on, since it's available after v3.
=> update ada-url to v3.2.1

Telegram/SourceFiles/platform/linux/tray_linux.cpp
QIcon::fromTheme overload with a fallback does a smarter check whether the icon is valid, use it to prevent getting a half-valid QIcon.
Should fix #29131 (but not sure)
=> Let QIcon::fromTheme check whether the tray icon is valid

Telegram/build/prepare/prepare.py
The cherry-pick made in 9fd1f95ab88a90e8acde6d26b2f1d715961f5c24 broke mozjpeg's own WITH_CRT_DLL variable so we have to use the cmake one
=> Set CMAKE_MSVC_RUNTIME_LIBRARY for mozjpeg

.devcontainer.json, .gitignore
It's annoying to rebuild index after cleaning the build directory
=> Ensure clangd cache is out of build directory
